[REFACTOR] 8주차 피드백 반영
kakao-tech-campus-2nd-step3/Team15_BE pull request #106
Opened 2024-10-31 10:18 UTC by seolbin96

## PR 유형
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- Redis와 토큰블랙리스트 사용하여 JWT 토큰 만료
- 비즈니스 예외 적용 및 환경변수 사용하도록 리팩토링

## 이슈 링크
close #102

2024-10-31 15:27 UTC, Profile-exe requested changes
수고하셨습니다! 로그아웃 구현 과정에서 `redis`를 토큰 블랙리스트 관리 저장소로 활용하던데, `redis`를 사용하신 이유가 궁금합니다! 

추가로 코멘트 남겨드렸으니 확인 부탁드립니다.

2024-10-31 15:27 UTC, Profile-exe commented on src/main/java/kakao/rebit/wishlist/exception/BookWishlistNotFoundException.java
> +        new BookWishlistNotFoundException();
불필요한 개행이 있는 것 같습니다

2024-10-31 15:27 UTC, Profile-exe commented on src/main/java/kakao/rebit/wishlist/service/BookWishlistService.java
> +            .orElseThrow(() -> BookWishlistNotFoundException.EXCEPTION);
다른 도메인에서도 repository로 찾고 못찾으면 예외를 던지는 로직들을 `find~By~OrThrow`로 분리해 재사용했는데, 여기도 분리하면 좋을 것 같은데 어떻게 생각하시나요?

위에 `member`, `book`에서도 `find~By~OrThrow` 메서드들로 통일했으니 여기도 동일한 맥락의 로직이라 메서드로 분리하는것도 좋아보여서요.

2024-10-31 15:27 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
>      }
전달받은 토큰이 아닌 `RequestContextHolder`에서 토큰을 추출하고 사용하던데 이렇게 구현하신 이유가 궁금합니다.

2024-10-31 15:27 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
>      }
`jwtToken`을 사용하지 않는 것 같은데, 넘겨주는 이유가 있을까요? 넘겨주었다면 해당 값을 사용하는게 맞다고 생각합니다.

그리고 토큰을 추출하여 넘겨주는 경우 `ArgumentResolver`를 정의해서 추출한 토큰을 controller에서 받고 서비스로 넘기는 것도 좋아보이는데, 어떻게 생각하시나요?

2024-11-01 05:51 UTC, kangboom commented on src/main/java/kakao/rebit/auth/jwt/JwtTokenProvider.java
> +        return expirationDate.getTime();
```java
public long getExpiration(String token) {
    return extractClaim(token).getExpiration().getTime();
}
'''
이런 식으로 바로 리턴하는게 더 깔끔한 것 같습니다!

2024-11-01 05:58 UTC, kangboom requested changes
고생하셨습니다~ 

명덕님께서 언급하신 resolver를 통해 jwtToken 받아오기, 메서드 파라미터로 전달한 token 값 사용하기 이 부분 저도 생각이 동일해서 생각해보시고 수정하시면 좋을 것 같습니다!

추가적으로 이번 PR과는 상관없는데 member 관련해서 아직 예외 처리가 안되어있는 것 같아서 이것도 수정해주셨으면 좋겠습니다!

2024-11-01 07:46 UTC, seolbin96 commented on src/main/java/kakao/rebit/wishlist/exception/BookWishlistNotFoundException.java
> +        new BookWishlistNotFoundException();
[cf3a4d5](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/106/commits/cf3a4d53b53d212d9ad2349349818154e9300f97)
수정했습니다!

2024-11-01 07:47 UTC, seolbin96 commented on src/main/java/kakao/rebit/wishlist/service/BookWishlistService.java
> +            .orElseThrow(() -> BookWishlistNotFoundException.EXCEPTION);
앗 그렇다면 여기서도 분리하는 게 좋을 것 같습니다!!
[3c7c135](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/106/commits/3c7c135bca532787eed1d15d7225814a421e8c1d) 수정했습니닷

2024-11-01 07:53 UTC, seolbin96 commented on src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
>      }
처음에 파라미터로 전달하지 않고 Authorization 헤더에서 직접 토큰을 추출했었는데 수정 과정에서 파라미터를 추가해놓고 이부분도 그대로 사용했습니다..! 이미 메서드에 jwtToken이 전달되고 있으니 이 부분은 필요하지 않네요! 수정했습니닷
[02a5be3](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/106/commits/02a5be352ddcb1185a2572b61a94c063f93fb00f)

2024-11-01 07:54 UTC, Profile-exe commented on src/main/java/kakao/rebit/wishlist/service/BookWishlistService.java
> +            .orElseThrow(() -> BookWishlistNotFoundException.EXCEPTION);
`findByOrThrow` 메서드들은 `Service`에 있습니다. `Repository`에 작성한 이유가 있으신가요?
다른 서비스에서도 해당 메서드들을 사용할 때 서비스 내에 정의 후 사용하고있습니다.

2024-11-01 07:58 UTC, seolbin96 commented on src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
>      }
`kakaoAuthService.kakaoLogout(jwtToken);` 에서 토큰을 블랙리스트에 추가하고 있습니다!!
ArgumentResolver 사용하는 부분에 대해서 저도 동의합니다. 현재 코드를 수정하는 중인데 계속해서 에러가 발생하고 있습니다 ㅜ_ㅜ 6시를 넘길 수도 있을 것 같아 코멘트 우선 남깁니다..! 수정되는 대로 푸쉬하겠습니다,,

2024-11-01 07:59 UTC, seolbin96 commented on src/main/java/kakao/rebit/auth/jwt/JwtTokenProvider.java
> +        return expirationDate.getTime();
[7c52476](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/106/commits/7c5247673880e72384210fe1ab8f16d9e0bfb846)
바로 리턴하는 게 훨씬 깔끔해보이네요! 반영했습니닷!

2024-11-01 08:06 UTC, seolbin96 commented
> 수고하셨습니다! 로그아웃 구현 과정에서 `redis`를 토큰 블랙리스트 관리 저장소로 활용하던데, `redis`를 사용하신 이유가 궁금합니다!
> 
> 추가로 코멘트 남겨드렸으니 확인 부탁드립니다.

로그아웃을 처음 구현해보아서 여러 블로그를 참고해봤는데 `redis`를 사용하는 것을 종종 볼 수 있었습니다! 로그아웃 시 redis를 사용하는 이유는 여러 가지가 있었는데 속도가 빠르고 TTL도 제공하고 있어서 개인적으로 이번에 사용하면서 공부해보고 싶은 마음에 사용해보았습니닷..ㅎㅎ

2024-11-01 10:22 UTC, merged