[FEAT] 로그인한 사용자가 각 피드에 대해 좋아요를 눌렀는지 여부를 확인하는 기능 추가
kakao-tech-campus-2nd-step3/Team15_BE pull request #121
Opened 2024-11-03 06:23 UTC by kangboom

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- 로그인한 사용자가 좋아요를 눌렀는지 확인하는 `isLiked` 메서드 추가
- `FeedResponse`에 isLiked 필드 추가
- 토큰이 있을 경우 멤버 정보를 받아오고 없을 경우는 null을 반환하는 `OptionalMemberResolver`리졸버 구현

## 이슈 링크
close #120 

## 참고사항
기존에 `LikesService`에서 피드에 대한 정보를 받아올 때,  `FeedService`를 주입 받고  `findFeedByIdOrThrow`를 호출하여 받아왔습니다.

하지만 이번 기능을 구현하면서 `FeedResponse`의 `isLiked `필드를 채우기 위해 `FeedMapper`에서 `LikesService`를 의존하게 되었는데 이에 따라 FeedService -> FeedMapper -> LikesService -> FeedService의 의존 관계가 생성되면서 순환 참조 오류가 발생했습니다.

이를 해결하고자 `LikesService`에서 `Feed `정보를 받아올 때, `FeedService`가 아닌 `FeedRepostiory`에서 받아오도록 구현했는데 더 좋은 방법이 있을지 피드백 부탁 드립니다!

2024-11-04 04:33 UTC, Profile-exe requested changes
수고하셨습니다! 코드도 깔끔하고 비즈니스 예외 적용 및 리팩터링도 해주셔서 감사합니다.

> 하지만 이번 기능을 구현하면서 FeedResponse의 isLiked 필드를 채우기 위해 FeedMapper에서 LikesService를 의존하게 되었는데 이에 따라 FeedService -> FeedMapper -> LikesService -> FeedService의 의존 관계가 생성되면서 순환 참조 오류가 발생했습니다.
> 
> 이를 해결하고자 LikesService에서 Feed 정보를 받아올 때, FeedService가 아닌 FeedRepostiory에서 받아오도록 구현했는데 더 좋은 방법이 있을지 피드백 부탁 드립니다!

여기에 대해 답변드리자면 

1. `FeedMapper` 에서의 `LikesService` 의존

    먼저 `FeedMapper`에서 `LikesService`에 의존하는게 좋지 않다 생각합니다. `Mapper`에 필요한 정보를 제공하는 것은 외부에서 이루어져야 한다고 생각합니다. 
  
    코멘트를 남겨드렸는데, `isLiked` 필드는 `Mapper`의 정적 메서드를 호출하는 외부에서 주어야지, `Mapper`에서 `LikesService`를 의존하여 데이터를 가져오는건 부적절하다 생각합니다.
  
    `Mapper`는 말 그대로 매핑만 시켜야 한다고 생각합니다.

2) `LikeService` 에서의 `FeedService` 의존

    `LikesService`에서는 `FeedService`나  `FeedRepository`를 의존하지 않아도 된다고 생각합니다. 
    
    `feedId`를 바탕으로 `Feed`를 조회한다면 이는 `FeedService`에서 넘겨주어야 하는 것이라 생각합니다.
    
    `FeedController`에서 `/api/feeds/{feed-id}/likes` 엔드포인트를 예로 들자면, `FeedService`에서 `getLikesMembers` 메서드를 만들고 

    1) 회원과 피드를 조회한 뒤, `LikesService`에서 피드들로 좋아요 누른 정보를 조회하고
    2) 해당 좋아요를 누른 회원들을 반환하는 방식으로 바꾼다면 
    
    `LikeService`에서 `FeedService`에 의존하는 순환 참조는 사라지게 됩니다.

    ```java
    @Operation(summary = "좋아요 누른 멤버 목록 조회", description = "해당 피드에 좋아요를 누른 멤버 목록을 조회합니다.")
    @GetMapping("/{feed-id}/likes")
    public ResponseEntity<Page<LikesMemberResponse>> getLikesMembers(
            @Parameter(hidden = true) @MemberInfo MemberResponse memberResponse,
            @PathVariable("feed-id") Long feedId,
            @PageableDefault(sort = "createdAt", direction = Sort.Direction.DESC) Pageable pageable) {
        return ResponseEntity.ok()
                .body(feedService.getLikesMembers(memberResponse, feedId, pageable));
    }
    ```

2024-11-04 04:33 UTC, Profile-exe commented on src/main/java/kakao/rebit/member/resolver/OptionalMemberResolver.java
> +        }
바로 `request.getHeader(AUTHORIZATION_HEADER))`를 `token`으로 받고 `null` 여부를 확인한다면 `extractTokenIfTokenPresent` 등의 메서드도 불필요할 것 같습니다! 로직이 중복된 것 같습니다.

2024-11-04 04:33 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/MagazineService.java
>      }
1. `pageable`에 따라 피드를 먼저 찾고 

2. `memberResponse`가 `null`이 아닌 경우 `LikeService`를 통해서 `findByMemberAndFeedIds` 등으로 해당 회원이 피드에 좋아요를 눌렀는지 확인해서 순회하며 좋아요 여부를 넣어주고

3. 피드 목록을 반환하는건 어떨까요?

아래는 그냥 대충 짠 예시인데 이렇게 가능할 것 같아서요

```java
public Page<Feed> getFeeds(MemberREspo, Pageable pageable) {
    // 1. 페이징된 피드 조회
    Page<Feed> feedPage = feedRepository.findAll(pageable);
    List<Feed> feeds = feedPage.getContent();

    if (!feeds.isEmpty()) {
        if (memberResponse != null) {
            // 2. 좋아요 상태 설정
            Set<Long> likedFeedIds = likeService.findByMemberAndFeeds(member, feeds);
    
            feeds.forEach(feed ->
                    feed.setLiked(likedFeedIds.contains(feed.getId()))
            );
        }
    }

    return feedPage;
}
```

2024-11-04 04:33 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
>      }
이러면 피드 목록 조회 시 각 요소마다 계속 데이터베이스를 조회할 것 같은데, In 쿼리로 한 번에 조회하는 방식으로 하고 여기서는 파라미터로 `isLiked`를 넘겨받는건 어떨까요?

2024-11-04 16:29 UTC, kangboom commented on src/main/java/kakao/rebit/member/resolver/OptionalMemberResolver.java
> +        }
[211f6b0](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/121/commits/211f6b0a8e2fd97796e19989629e5a029b562937)
[070bb3a](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/121/commits/070bb3ae549629a9bd709e40b5fd9bfb10cdacb4)
반영했습니다!

2024-11-04 16:30 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/MagazineService.java
>      }
[514fc11](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/121/commits/514fc112328cffa76cd544184811e5c86045ccf8) : 반영했습니다!

2024-11-04 16:31 UTC, kangboom commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
>      }
[1f40aea](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/121/commits/1f40aea38d6e6cb9d8844256053e352bfa240618)
[514fc11](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/121/commits/514fc112328cffa76cd544184811e5c86045ccf8)
 : 반영했습니다

2024-11-05 00:08 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/entity/Likes.java
> +    }
정적 팩토리 메서드는 매개변수가 여러개인 경우 `of`, 하나인 경우 `from`으로 적는 관행이 있는데, 저희도 이런 부분을 통일시키면 좋을 것 같습니다.

[참고자료](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90) 링크 보내드립니다.

강범님은 어떻게 하고 싶으신가요??

2024-11-05 02:23 UTC, kangboom commented on src/main/java/kakao/rebit/feed/entity/Likes.java
> +    }
[dc06c9d](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/121/commits/dc06c9d082cd5babadabaa7fbc96e91e5397aca4) : 네이밍 규칙에 맞춰서 하는 게 더 좋을 것 같습니다! 반영했습니다~

2024-11-05 02:58 UTC, Profile-exe approved these changes
수고하셨습니다!

2024-11-05 09:40 UTC, merged