[FEAT] 챌린지 조회, 생성, 삭제 구현
kakao-tech-campus-2nd-step3/Team15_BE pull request #20
Opened 2024-09-25 01:39 UTC by Profile-exe

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- 챌린지 엔티티 조회, 생성, 삭제 API 구현
- 회원 엔티티 `username` 필드를 ERD에 맞게 `nickname`으로 수정

## 이슈 링크
close #19

2024-09-25 07:58 UTC, kangboom requested changes
고생하셨습니다~~

2024-09-25 07:58 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/controller/ChallengeController.java
> +        return ResponseEntity.created(URI.create("/challenges/" + challengeId)).build();
이렇게 생성된 자원의 URI를 응답으로 주는 이유가 뭔지 궁금합니다!

2024-09-25 07:58 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/dto/ChallengeRequest.java
> +        Integer maxHeadcount
primitive와 wrapper 중 wrapper 타입을 쓴 이유가 궁금합니다.

2024-09-25 07:58 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/service/ChallengeService.java
> +    @Transactional(readOnly = true)
전 보통 `@Transcation(readOnly=true)` 를 클래스 범위로 선언하고 수정이 필요한 메서드에만 따로 선언해주는데`@Transacntion`을 클래스 범위로 선언하지 않고 각 메서드 마다 선언 해주는 특별한 이유가 있나요??..

2024-09-25 07:58 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/service/ChallengeService.java
> +    }
리턴 값으로 Id를 주는 이유가 궁금합니다.

2024-09-25 07:58 UTC, kangboom commented on src/main/java/kakao/rebit/member/service/MemberService.java
> +    public Member findMemberByIdOrThrow(Long memberId) {
메서드명 직관적이어서 되게 좋네요~~

2024-09-25 07:58 UTC, kangboom commented on src/main/java/kakao/rebit/member/service/MemberService.java
> +    }
개발 어느정도 진행되면 Exception에 대한 논의도 필요해보입니다.

2024-09-25 08:07 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/controller/ChallengeController.java
> +        return ResponseEntity.created(URI.create("/challenges/" + challengeId)).build();
`ResponeEntity`에서 `201` 응답을 줄 때, `created` 메서드가 있어서 이를 활용하려 했습니다.

매개변수로 `URI` 객체를 받길래 해당 상태코드에 대한 [MDN docs - 201 Created](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201) 문서를 확인했는데, 

> 응답 메시지 본문에 새로 만들어진 리소스 혹은 리소스에 대한 설명과 링크를 메시지 본문에 넣어 반환합니다. 그 위치는 요청 URL 또는 [Location](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Location) 헤더 값의 URL 입니다.

위 내용을 읽고 자원 생성 시 해당 자원에 접근할 수 있는 `URI`를 넘겨주면 좋겠다고 생각했습니다!

2024-09-25 08:43 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/dto/ChallengeRequest.java
> +        Integer maxHeadcount
해당 `DTO`는 `@RequestBody`를 이용해 요청 본문에 포함되는 내용들과 매핑됩니다.

`Integer`일 때, `minHeadcount` 필드가 없다면 `null`이 들어가고, `primitive` 타입이라면 `int`의 기본값인 `0`이 들어갑니다.
`null`이라면 `@Valid`, `@NotNull`을 활용해 검증이 가능합니다.

`primitive` 타입일 때 값이 누락되어 0이 담긴 경우에는 실제로 최소 모집 인원을 0으로 한건지, 오류로 인해 0이 담긴건지 구분하기 어렵습니다.

이런 상황들을 고려해 `wrapper` 타입을 사용했습니다!

2024-09-25 08:51 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/service/ChallengeService.java
> +    @Transactional(readOnly = true)
다음과 같은 상황때문에 적용했습니다.

1. `@Transactional` 어노테이션이 붙은 메서드는 DB connection이 필요한 로직으로 쉽게 인지
2. 붙지 않은 어노테이션은 DB와는 별개의 비즈니스 로직으로 쉽게 인지(어노테이션을 붙일 필요가 없음)
3. `@Transactional`이 붙은 메서드가 같은 클래스 내에서 호출되는 경우 `self-invocation` 문제가 발생하는데, 메서드마다 해당 어노테이션이 안붙어있다면 해당 상황에서 문제가 발생하는지 빠르게 인지하기 어려움.

따라서 필요한 곳에만 어노테이션을 사용해 메서드의 정보(트랜잭션 사용/미사용 등)를 바로 확인할 수 있고, `self-invocation` 문제 또한 바로 인지할 수 있다는 점 때문에 이렇게 구현했습니다!

2024-09-25 08:53 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/service/ChallengeService.java
> +    }
[해당 답변](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/20#discussion_r1774764638) 에 말씀드린 것처럼 자원의 접근 경로를 제공하기 위해 `id`를 반환했습니다.

챌린지 상세 정보에 대한 `URL`이 `~/challenges/{challengeId}`라서 이에 맞추어 반환하려고 했습니다.

2024-09-25 08:54 UTC, Profile-exe commented on src/main/java/kakao/rebit/member/service/MemberService.java
> +    }
넵 제가 다른 프로젝트에 작성해본 예외처리로직이 있는데, 함께 만나서 이에 대해 논의해보고싶습니다.

2024-09-25 09:58 UTC, Wonmoan approved these changes
주석이 잘 적혀있어 좋았습니다.
고생하셨습니다~~~

2024-09-25 09:58 UTC, Wonmoan commented on src/main/java/kakao/rebit/challenge/dto/ChallengeRequest.java
> +        String content,
1. DTO에서 필수 입력 값에 대한 유효성 검사를 두실 계획이 있으신가요?
2. ChallengeType (ex `일일 글쓰기`, `릴레이 소설`, `작가의 문장 이어서 적어보기` 같이 저희가 어느정도 구성해놓은 타입을 별도로 정의해서 활용하는 것도 좋을 것 같습니다!

2024-09-25 10:39 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/dto/ChallengeRequest.java
> +        String content,
1. 네 예외처리 로직을 추가한 뒤에 여유가 된다면 `DTO`에 검증을 적용하고싶습니다.
2. 의견 감사합니다. `ChallengeType`으로 현재 해당 내용을 담고있긴 한데, 열거형 내용을 조금 수정해달라는 말씀이실까요?

2024-09-25 11:30 UTC, Wonmoan commented on src/main/java/kakao/rebit/challenge/dto/ChallengeRequest.java
> +        String content,
잘 작성되어있네요 ! 확인했습니다! 고생하셨습니다. 😊

2024-09-26 07:04 UTC, kangboom approved these changes

2024-09-26 07:14 UTC, merged