[FEAT] 피드 조회 구현
kakao-tech-campus-2nd-step3/Team15_BE pull request #24
Opened 2024-09-26 14:30 UTC by kangboom

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- feed 전체 조회, 상세 조회 구현
- 응답을 위한 dto 구현

## 이슈 링크
close #16 

## 참고사항
- Feed 연관 관계로 인해 Book 기본키 수정했습니다.
- DTO record로 만드려고 했으나 상속으로 구현하는 게  중복 코드도 줄이고 피드를 한번에 조회할 때 다형성을 사용하는게 더 좋다고 생각해서 일반 class로 구현하였습니다.  이 부분에 대해서는 더 좋은 방법이 있을지 의견 듣고 싶습니다.
- Feed와 Feed 하위 항목들을 묶어서 한번에 컨트롤러, 서비스를 작성할지 아니면 각각 작성할지 고민하다가 그냥 각각 작성하는 게 저는 보기 더 편한 것 같아서 각각 작성했는데 다른 분들은 어떻게 생각하시는지 궁금합니다.

2024-09-26 15:09 UTC, Profile-exe requested changes
전반적으로 코드가 깔끔해서 보기 편했습니다!  코멘트 남겨드렸으니 확인 부탁드려요 ㅎㅎ

2024-09-26 15:09 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/dto/response/FeedResponse.java
> +    private BookResponse bookResponse;
의미있는 이름을 짓는게 좋을 것 같아요! 현재 응답을 확인해보면 `memberResponse`, `bookResponse`로 오는데, `author`, `book` 으로 짓는건 어떠신가요?
제가 챌린지 API에서 챌린지 생성자를 의미하는 `creator`로 회원 정보를 반환하는데 이처럼 의미 있는 식별자를 활용하면 좋을 것 같습니다!

추가로 `MemberResponse`의 경우 회원 정보를 조회할 떄 사용하게 되는데, 그래서 `bio`, `role`, `point` 등 불필요한 정보가 함께 포함됩니다.
`Feed` 도메인만을 위한 회원 정보 반환 `DTO`를 만들어보는건 어떠신가요?

2024-09-26 15:09 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/entity/Feed.java
> +    private String type; // 상속 관계로 인해 생성된 type을 조회하기 위한 필드
`DiscriminatorColumn`을 이렇게 조회할 수 있군요! `insertable`, `updatable`로 제약조건을 준 것도 아주 좋은 것 같습니다. 👍

2024-09-26 15:09 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/repository/MagazineRepository.java
>  @Repository
`JpaRepository` 인터페이스를 상속하면 `@Repository` 없어도 돼요! 다른 곳에도 붙어있다면 제거하면 좋을 것 같습니다 ㅎㅎ

2024-09-26 15:09 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +    }
다른 클래스에서도 중복되는 코드네요, `Feed`에서 해당 메서드들을 `public`으로 열고 다른 서비스에서 재사용하는게 좋을 것 같은데 어떻게 생각하시나요?

2024-09-26 15:26 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +    }
아~ 그게 좋을 것 같습니다. dto 변환 로직은 private로 처리하는 습관이 있었는데 중복되는 경우 public으로 열어서 중복 코드를 줄이는 게 좋을 것 같습니다!

2024-09-26 15:34 UTC, Profile-exe commented
> DTO record로 만드려고 했으나 상속으로 구현하는 게 중복 코드도 줄이고 피드를 한번에 조회할 때 다형성을 사용하는게 더 좋다고 생각해서 일반 class로 구현하였습니다. 이 부분에 대해서는 더 좋은 방법이 있을지 의견 듣고 싶습니다.

`Feed`의 명세가 바뀌면 `DTO`도 함께 바뀌어야 할텐데, 상속을 통해 변경될 부분을 최소화할 수 있을 것 같아 `class` 사용도 좋아보입니다!

> Feed와 Feed 하위 항목들을 묶어서 한번에 컨트롤러, 서비스를 작성할지 아니면 각각 작성할지 고민하다가 그냥 각각 작성하는 게 저는 보기 더 편한 것 같아서 각각 작성했는데 다른 분들은 어떻게 생각하시는지 궁금합니다.

상속 관계인 만큼 `Feed`와 그 하위 항목들은 깊은 연관관계가 있을텐데 클래스를 분리하더라도, 엔드포인트는 `RESTful`하게 `/api/feeds/`로 시작하는 것도 괜찮아보입니다.

- `/api/feeds`
- `/api/feeds/favorite-books`
- `/api/feeds/storeis`
- `/api/feeds/magazines`

엔드포인트를 위와 같이 설정하는 것에 대해 어떻게 생각하시나요?

2024-09-26 16:15 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +    }
[ee94d84](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/24/commits/ee94d8466ba6462d240ea3065a41f8d943661426) feedService에서 public으로 열어서 사용하도록 했습니다.

2024-09-26 16:16 UTC, kangboom commented on src/main/java/kakao/rebit/feed/dto/response/FeedResponse.java
> +    private BookResponse bookResponse;
[7a9d50d](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/24/commits/7a9d50dd9616db9ddcd8353d53c27d939cbb7517) feed 도메인 전용 dto 만들었습니다.

2024-09-26 16:17 UTC, kangboom commented on src/main/java/kakao/rebit/feed/repository/MagazineRepository.java
>  @Repository
[ea66b96](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/24/commits/ea66b96b7e7da8de1a7de4d5c775fe7b83bc13a0) 삭제했습니다.

2024-09-26 16:22 UTC, kangboom commented
저도 피드 하위 항목들은 피드와 묶어서 `/api/feeds/*` 로 시작하는 게 큰 범주 안의 feed 도메인을 설명하는데 있어 더 좋다고 생각합니다. 헤딩 부분 반영했습니다.
[aef0634](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/24/commits/aef0634cbb23d1b237015ba2608e1e9cfd9141d8)

2024-09-26 16:58 UTC, Profile-exe approved these changes
빠른 피드백 감사드립니다 🔥 수고하셨습니다!

2024-09-27 08:19 UTC, seolbin96 reviewed
수고하셨습니다!! 제가 더 달 코멘트가 없는 것 같네욥..

- record 대신 상속으로 구현하여 중복 코드를 줄이는 거 좋은 것 같습니다 !
- 저도 Feed와 하위 항목들을 각각 작성하는 게 더 보기 편하다고 생각합니다. 유지보수도 더 편할 것 같아요.

- 추가로 저희 코드 가장 마지막 줄에 줄바꿈 추가하도록 하지 않았었나요?? 강범님 코드에 마지막 줄바꿈이 없는 것 같아 여쭤봅니당

2024-09-27 09:09 UTC, seolbin96 approved these changes

2024-09-27 10:06 UTC, merged