[FEAT] 피드 생성, 수정, 삭제 구현
kakao-tech-campus-2nd-step3/Team15_BE pull request #40
Opened 2024-09-29 14:49 UTC by kangboom

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- 피드 생성, 수정, 삭제 구현
- 변환을 위한 Mapper 클래스 생성
- `KakaoAuthController`의 `@RequestParam` 쿼리 파라미터 이름 명시

## 이슈 링크
close #25 

## 참고 사항
![image](https://github.com/user-attachments/assets/13d88771-f2fc-4821-b662-46c0b406b322)
피드 생성 시, JSON 값으로 `"type": 피드 종류(FB, M, S)` 를 넘겨줘야 된다.

![image](https://github.com/user-attachments/assets/e348f907-8795-4c5c-926e-63558f9ca894)
수정 또한 마찬가지로 `"type": 피드 종류(FB, M, S)` 를 넘겨줘야 된다.

수정에 대해서 많이 고민했습니다. 
1. 지금 코드처럼 Dto를 다형성을 살려서 상속 구조로 설계한 뒤 UpdateXXXRequest를 각 Feed로 변환 시켜 도메인의 `updateNonNullFields()`에 넘겨서 오버라이딩을 통해 각각의 도메인에서 Null이 아닌 값들만 수정되도록 한다.

장점
- 엔드포인트가 `"/api/feeds/{feed-id}"` 하나로 통일된다.
- 서비스도 하나로 통일된다.
- 코드 중복이 사라지고 짧아진다.

단점
- `@Requestbody`로 받은 Dto 데이터를 검증할 때, bookId 필드는 인생책에서는 필수지만 메거진, 스토리에서는 필수가 아니기 때문에 Dto에서 바로 검증을 할 수 없다. 따로 service에서 인생책만 따로 검증을 해야 된다.
- Dto-Entity 간의 변환 코드가 많아진다.
- update 할 때는 객체를 전부 넘겨주는 것 보다 수정하고자 하는 필드 값을 넘겨주는 게 좋다고 배웠는데 다형성을 살리려면 부모 객체를 넘겨줘야 된다. 

2. 그냥 엔드포인트를 따로 작성해서 타입마다 각각 Dto와 Service를 만들고 Update 함수에 필드 값을 직접 넣어서 수정한다. 

장점
- 검증을 각 피드 특성에 맞게 세밀하게 할 수 있음
- 수정하고 하는 필드 값만 넘겨줘서 수정할 수 있다.

단점
- 중복 코드가 많아짐
- 코드가 길어짐
- 상속 관계의 이점을 잘 사용하지 못함

제가 잘못 생각하고 있거나 더 괜찮다고 생각하는 방법이 있으면 많은 피드백 부탁드립니다..

2024-09-29 16:06 UTC, Profile-exe requested changes
서비스쪽 코드가 훨 깔끔해진 것 같습니다! 

`PUT`메서드로 수정을 진행하는데, `PATCH` 메서드 요청처럼 구현하느라 불필요한 로직이 포함된 것 같아요! 요청에 대한 모든 필드값들이 있다고 생각하고 구현하시면 깔끔하게 작성될 것 같습니다.

`updateNonNull`에서 `NonNull` 확인 로직이 필요한지 함께 의논해보면 좋을 것 같습니다.

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/entity/FavoriteBook.java
> +        }
이 부분은 다른 엔티티에서도 중복되는 것 같은데, `Feed`의 `updateNonNullFields`에 `null` 확인 분기를 두고 `super`도 무조건 호출하도록 하는건 어떤가요?

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/entity/Feed.java
> +    }
수정 엔드포인트는 `PUT` 메서드를 사용하고 있습니다. 부분 수정인 `PATCH`와 달리 `PUT`은 리소스 전체 데이터를 덮어씌우기 때문에, `NonNull` 필드만 수정하는게 맞는지, 그렇기에 이 메서드명과 기능이 적절한지 생각해보시면 좋을 것 같습니다.

프론트에서 수정 요청 시 기존의 본문 내용도 함께 가져와서 내용 전체를 덮어씌우는게 `PUT`에 가깝다고 생각합니다!
즉, `PUT`에서는 어떤 필드가 수정되었는지 몰라도 되는 것이죠

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/entity/Magazine.java
> +    }
`null` 체크가 불필요하겠지만, 다음과 같이 `switch` 구문을 이용할 수 있겠네요! `null` 확인때문에 적용되는 부분이라, `PUT` 메서드의 특성을 이용한다면 불필요한 코드이긴 합니다.

```java
@Override
public void updateNonNullFields(Feed feed) {
    super.updateNonNullFields(feed);

    switch (feed) {
        case Magazine m when m.getName() != null -> this.name = m.getName();
        case Magazine m when m.getImageUrl() != null -> this.imageUrl = m.getImageUrl();
        case Magazine m when m.getContent() != null -> this.content = m.getContent();
        default -> throw new IllegalStateException("올바르지 않은 타입입니다.");
    }
}
```

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +                    .orElseThrow(() -> new IllegalArgumentException("해당 책이 존재하지 않습니다."));
중복되는 `BookRepository`의 메서드 호출보다는 `BookService`에서 해당 로직을 `findBookByIdOrThrow` 메서드로 만들어 재사용하면 좋을 것 같네요!

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +    }
아래 메서드를 정의했으니 이를 재사용하는건 어떨까요?
```java
public FeedResponse toFeedResponse(Feed feed) {
    switch (feed) {
        case FavoriteBook favoriteBook -> {
            return toFavoriteBookResponse(favoriteBook);
        }
        case Magazine magazine -> {
            return toMagazineResponse(magazine);
        }
        case Story story -> {
            return toStoryResponse(story);
        }
        default -> throw new IllegalStateException("유효하지 않는 피드입니다.");
    }
}
```

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +    }
여기도 `switch` 구문 사용과 메서드 분리로 좀 더 가독성 있게 바꿀 수 있을 것 같습니다.
```java
    // 각 하위 클래스 생성
    return switch (feedRequest) {
        case UpdateFavoriteBookRequest favoriteBookRequest -> createFavoriteBook(member, book, favoriteBookRequest);
        case UpdateMagazineRequest magazineRequest -> createMagazine(member, book, magazineRequest);
        case UpdateStoryRequest storyRequest -> createStory(member, book, storyRequest);
        default -> throw new IllegalStateException("유효하지 않는 피드 요청입니다.");
    };
}

private FavoriteBook createFavoriteBook(Member member, Book book, UpdateFavoriteBookRequest request) {
    return new FavoriteBook(member, book, request.getBriefReview(), request.getFullReview());
}

private Magazine createMagazine(Member member, Book book, UpdateMagazineRequest request) {
    return new Magazine(member, book, request.getName(), request.getImageUrl(), request.getContent());
}

private Story createStory(Member member, Book book, UpdateStoryRequest request) {
    return new Story(member, book, request.getImageUrl(), request.getContent());
}
```

위쪽에 생성을 위한 `toFeed` 메서드에서도 이러한 로직을 적용시키면 더 깔끔할 것 같네요! ㅎㅎ

2024-09-29 16:06 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
수정을 할 때 필요한 데이터들이 `request`에 존재할텐데, 엔티티로 바꾸고 `update` 메서드를 호출하는 이유가 있을까요?
저는 바로 `feed.updateNonNullFields(feedRequest)` 이런식으로 구현하는게 더 적절하다 생각하는데 강범님 의견은 어떠신가요?

2024-09-30 06:03 UTC, kangboom commented on src/main/java/kakao/rebit/feed/entity/Feed.java
> +    }
처음에는 `PUT`의 의미를 살려 전체 내용을 받아서 수정하려는 목적으로 구현했으나, 구현하던 중 프론트에서 어떤 식으로 수정 데이터를 받을 지 정해지지 않아서 `null`을 확인하는 로직을 추가하였습니다... 프론트에서 강제한다고 하면 `null` 확인 로직을 삭제하고 그냥 DTO에서 `@Valid`를 사용해 검증하면 훨씬 더 코드가 깔끔해질 것 같네요! 앞으로 개발할 때, HTTP 메서드의 의미를 살려서 개발하면 더 좋은 코드가 되겠네요~~  감사합니다.

2024-09-30 16:01 UTC, Wonmoan reviewed
`DTO`와 `엔티티` 간의 분리도 잘되어있고 전체적으로 재사용성 높은 구조로 잘 작성하셔서 코드 리뷰하면서 저도 많이 배울 수 있었습니다.
 
금일 진행된 회의에서 프론트쪽과 null로직에 관련해서 확립한 것으로 알고 있습니다. 
코드 살펴보며 수정 메서드에 관해서 함께 고민해 볼 수 있었던 것 같습니다. 

null 로직과 연관된 수정사항이 대부분이라,  추가적인 코멘트는 따로 남기지 않겠습니다.
고생하셨습니다!

2024-09-30 16:05 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +                    .orElseThrow(() -> new IllegalArgumentException("해당 책이 존재하지 않습니다."));
해당 메서드 구현해서 재사용 할 수 있도록 5주차에 반영하겠습니다.

2024-09-30 16:05 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
현재 방식은 `feed` 객체 생성후 업데이트 하는 방식인 것 같습니다. 
`객체를 여러번 생성` -> `기존 엔티티 값 직접 수정` 하는 방식도 좋은 방법이 될 것 같습니다.

2024-10-01 13:58 UTC, kangboom commented on src/main/java/kakao/rebit/feed/entity/FavoriteBook.java
> +        }
[70fc761](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/40/commits/70fc761d52751914d6af38c02543db4f8298b5c9) 
[dc55463](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/40/commits/dc554637ef2a5b7dbb9f2fa1cae08ab77a3fb119) 
책을 수정하는 메서드인 `changeBook` 을 만들어서 통일 시켜줬고 검증은 service에서 처리되도록 구현했습니다.

2024-10-01 14:00 UTC, kangboom commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +    }
[df76cd2](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/40/commits/df76cd2263ed6971bc3889c397d42dfa1cb5ab1a)
수정했습니다.

2024-10-01 14:00 UTC, kangboom commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +    }
[df76cd2](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/40/commits/df76cd2263ed6971bc3889c397d42dfa1cb5ab1a)
마찬가지로 반영했습니다.

2024-10-01 14:02 UTC, kangboom commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +                    .orElseThrow(() -> new IllegalArgumentException("해당 책이 존재하지 않습니다."));
[dbf8fb7](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/40/commits/dbf8fb75dc10f4ff46eed1f5595a5152303e2f65)
알고도 남겨두기 좀 그래서 제가 반영했습니다!

2024-10-01 14:03 UTC, kangboom commented on src/main/java/kakao/rebit/feed/entity/Magazine.java
> +    }
null 체크는 따로 하지 않는 것으로 반영했습니다.

2024-10-01 14:06 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
`객체를 여러번 생성 `-> `기존 엔티티 값 직접 수정`이 부분이 잘 이해가 안되는데 제가 지금 하고 있는 방식이 객체를 여러번 생성하는 방식이고 기존 엔티티 값을 직접 수정하는 방식으로 하면 좋겠다는 말씀이신가요?..

2024-10-01 14:09 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
명덕님 궁금한 게 있는데, 제가 entity에 dto의 의존성이 생기는 것이 dto를 넘기고 싶지 않은 이유 중 하나라고 말씀 드렸을 때 dto - entitiy 간의 변환은 mapper가 담당하고 있어서 상관없다? 이런 느낌으로 말씀하신 것 같은데 잘 이해가 안돼서요.. 혹시 조금만 더 설명해주실 수 있을까요?

2024-10-01 14:14 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
`entity`와 `dto`의 생성자들이 서로를 매개변수로 갖지 않고, 필요한 필드들만 갖게 된다면 `Mapper`에서는 변환 시 필요한 필드만 꺼내서 각 생성자로 넘겨줄 수 있습니다. 따라서 `entity`나 `dto`에서 서로를 "몰라도" 변환이 가능하기 때문에 의존성이 생기지 않습니다.

만약 `Mapper` 클래스를 사용하더라도 생성자에서 `entity`와 `dto`가 서로를 매개변수로 받고 생성자 안에서 필요한 필드를 꺼내서 할당하는 로직이 존재한다면, `Mapper`가 존재하는 의미가 사라진다고 봅니다!

2024-10-01 14:25 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
생성자 뿐만 아니라 다른 메서드에서도 `dto`를 매개변수로 갖게 된다면 의존성이 생긴다고 봐야 되는 거 아닌가요??..

2024-10-01 14:49 UTC, Profile-exe requested changes
`FeedResponse`를 반환하면서 더욱 코드가 간결해진 것 같습니다! 코멘트 남겨드렸으니 확인 부탁드려요 ㅎㅎ

2024-10-01 14:49 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
`BookService`에 `@Transactional` 어노테이션이 하나도 없는데, 추가해주시면 감사하겠습니다!

2024-10-01 14:49 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +    }
`null`을 다룬다면 `Optional`을 사용하는건 어떤가요?
```java
        findBookIfBookIdExist(feedRequest.getBookId()).ifPresent(feed::changeBook);  // ifPresent 사용!
        feed.updateAllExceptBook(feedRequest);
    }

    // ...

    private Optional<Book> findBookIfBookIdExist(Long bookId) {
        if (bookId != null) {
            Book book = bookService.findBookByIdOrThrow(bookId);
            return Optional.of(book);
        }
        return Optional.empty();
    }
```

2024-10-01 14:49 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/entity/Feed.java
> +    public abstract void updateAllExceptBook(UpdateFeedRequest feedRequest);
추상 메서드로 구현을 강제하는 부분 좋습니다 👍

2024-10-01 14:49 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        }
로직이 `updateFeed`와 중복되네요. 메서드로 추출하면 좋을 것 같고, `@Valid` 어노테이션을 이용해 해당 로직을 검증할 수 있을거라 생각하는데, 추후 `Validator` 적용을 고려해보면 좋을 것 같습니다!
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Constraint(validatedBy = FavoriteBookValidator.class)
public @interface ValidFavoriteBook {
    String message() default "인생책은 책이 반드시 필요합니다.";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

```java
public class FavoriteBookValidator implements ConstraintValidator<ValidFavoriteBook, FeedRequest> {
    @Override
    public boolean isValid(FeedRequest feedRequest, ConstraintValidatorContext context) {
        if (feedRequest instanceof FavoriteBookRequest) {
            return feedRequest.getBookId() != null;
        }
        return true;
    }
}
```

2024-10-01 14:49 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/controller/FavoriteBookController.java
> +    public ResponseEntity<Page<FeedResponse>> getFavoriteBooks(
`FeedResponse`를 반환해도 각 인스턴스의 필드가 온전히 반환되네요! 처음 알았습니다. 많이 배우네요 👍

2024-10-01 14:50 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        feed.updateNonNullFields(updateFeed);
네 `entity`나 `dto`의 어떤 메서드라도 서로 매개변수를 갖고 있다면 의존성이 생기는게 맞습니다!

2024-10-02 03:05 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        }
좋은 의견 감사합니다 :) 저도 이 코드가 비슷한 것 같아서 중복을 줄이기 위해 고민해보았는데 명덕님이 제안해주신 대로 하려면 CreatFeedRequest랑 UpdateFeedRequest를 FeedRequest 클래스를 만들어서 상속 구조로 묶어야 되는데 추후에 update와 create는 검증 로직에서 차이가 날 수 있다고 생각해서 상속 구조로 만들면 오히려 불편하겠다고 판단하여 그대로 두었습니다. 명덕님 의견은 어떠신가요? 그리고 만약 상속 구조를 사용하지 않아도 해결할 수 있는 방법이 있다면 알려주시면 감사하겠습니다!ㅎㅎ

2024-10-02 03:07 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +    }
`Optional`을 통해 이 메서드가 `null`을 반환할 수 있다는 점을 명시적으로 드러냄으로써 코드 명확성을 높일  수 있겠네요!

2024-10-02 03:28 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
> +        }
그러면 검증 어노테이션과 로직을 따로 두어서 `@ValidateCreateFavoriteBook`, `@ValidateUpdate~` 이렇게 만들어도 좋겠네요! 

`bookId` 여부를 판단하는 공통로직은 상속 없이 구현할 때, 아래 두 방법으로 구현 가능한 것 같습니다! `Cluade`에게 물어본 결과입니다.

- 방법 1
  ```java
  public class FavoriteBookValidator implements ConstraintValidator<ValidFavoriteBook, Object> {
      @Override
      public boolean isValid(Object object, ConstraintValidatorContext context) {
          if (object instanceof CreateFavoriteBookRequest || object instanceof UpdateFavoriteBookRequest) {
              Long bookId = null;
              if (object instanceof CreateFavoriteBookRequest) {
                  bookId = ((CreateFavoriteBookRequest) object).getBookId();
              } else {
                  bookId = ((UpdateFavoriteBookRequest) object).getBookId();
              }
              return bookId != null;
          }
          return true;
      }
  }
  ```

- 방법 2
  ```java
    public class FavoriteBookValidator implements ConstraintValidator<ValidFavoriteBook, Object> {
      
      private static final String BOOK_ID_GETTER = "getBookId";
  
      @Override
      public boolean isValid(Object object, ConstraintValidatorContext context) {
          return Optional.of(object)
                  .filter(this::isFavoriteBookRequest)
                  .map(this::getBookId)
                  .filter(Objects::nonNull)
                  .isPresent();
      }
  
      private boolean isFavoriteBookRequest(Object object) {
          return object instanceof CreateFavoriteBookRequest || 
                 object instanceof UpdateFavoriteBookRequest;
      }
  
      private Long getBookId(Object object) {
          try {
              Method getBookId = object.getClass().getMethod(BOOK_ID_GETTER);
              return (Long) getBookId.invoke(object);
          } catch (Exception e) {
              return null;
          }
      }
  }
```

2024-10-02 03:29 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/BookService.java
[13807dd](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/40/commits/13807dde3423d17be563ab97b025ef6ef39033de): 반영했습니다~

2024-10-02 03:33 UTC, Profile-exe requested changes

2024-10-02 03:33 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
>          feed.changeBook(book);
`Optional`의 이점을 살리려면, 제가 제안드린 코드처럼 변경하는게 좋다고 생각합니다. 현재 코드는 기존 코드와 달라진 점이 없는 것 같습니다!

```java
Book book = findBookIfBookIdExist(feedRequest.getBookId()).orElse(null);
feed.changeBook(book);
feed.updateAllExceptBook(feedRequest);
```

위 내용을 아래처럼 쓸 수 있습니다. `book`이 존재할때만 `changeBook`이 호출되는 이점과 함께 좀 더 명시적인 코드 작성이 가능합니다.

```java
findBookIfBookIdExist(feedRequest.getBookId()).ifPresent(feed::changeBook);
feed.updateAllExceptBook(feedRequest);
```

2024-10-02 03:39 UTC, seolbin96 approved these changes
명덕님이 남겨주신 마지막 코멘트만 수정하면 될 것 같아서 바로 approve 하겠습니다. 수고하셨습니다!!

2024-10-02 05:34 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
>          feed.changeBook(book);
`changBook`은 book이 존재할 때만이 아닌 `null` 일 때도 사용되어 메거진이나 스토리에서 `null`로 업데이트 해줘야 됩니다. 따라서 `findBookIfBookIdExist`에서 만약 request에 `bookId`가 있으면 해당 book을 리턴해주고 `bookId` 가 없으면 `null`을 리턴해야 됩니다.

2024-10-02 05:56 UTC, Profile-exe approved these changes

2024-10-02 05:56 UTC, merged