[FEAT] 챌린지 참여 API 구현
kakao-tech-campus-2nd-step3/Team15_BE pull request #50
Opened 2024-10-02 02:29 UTC by Profile-exe

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- 챌린지 참여 구현
- 챌린지 참여 취소 구현
- 챌린지 참여 정보 조회 구현

## 이슈 링크
close #37 

## 참고사항
- `ChallengeParticipant`를 `ChallengeParticipation`으로 변경했습니다. 챌린지 "참여자" 보다는 챌린지 "참여"에 대한 정보를 나타내고 싶었습니다. 해당 부분은 ERD에도 반영하겠습니다.
- 현재 챌린지 도메인 로직은 `ArgumentResolver`가 없어 임의의 `MemberResponse`인스턴스를 사용중입니다. 추후 해당 부분이 구현된다면 수정하겠습니다.

2024-10-02 07:35 UTC, kangboom requested changes
고생하셨습니다~~

2024-10-02 07:35 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/repository/ChallengeParticipationRepository.java
> +    Page<ChallengeParticipation> findAllByChallenge(@Param("challenge") Challenge challenge, Pageable pageable);
`ChallengeParticipation` 엔티티는 그 자체로써 의미 있는 게 아니라 `Challenge`와 `Member` 사이를 이어주는 목적이기 때문에 필히 필드들을 참조해야 되므로 즉시 로딩으로 추가 쿼리가 발생하지 않도록 하여 성능을 높이는 목적으로 `@Query`를 사용한 건가요?

2024-10-02 07:35 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
챌린지와 사용자가 1대1로 매핑된 정보를 얻기 위한 메서드 인 것 같은데 이 메서드는 어떤 목적으로 사용되는 건지 궁금합니다.

2024-10-02 07:35 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
`participation-id`를 `PathVariable`로 받아서 참여 정보를 삭제 시키는 것은 `challenge_participation` 테이블에서 해당 챌린지와 멤버에 대응하는 `participation-id`를 찾아야 되는 로직이 필요하지 않나요?? 참여자가 직접 챌린지 참여를 취소한다면 해당 `challengeId` 와 참여자의 정보를 `Resolver`로 받아서 이 두 개의 정보로 삭제하는 건 어떻게 생각하시나요?

2024-10-02 07:35 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/service/ChallengeParticipationService.java
> +    }
검증 로직 꼼꼼히 작성해주신거👍

2024-10-02 07:53 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/repository/ChallengeParticipationRepository.java
> +    Page<ChallengeParticipation> findAllByChallenge(@Param("challenge") Challenge challenge, Pageable pageable);
넵 맞습니다! `fetch join`을 사용하기 위해 `@Query`를 사용했습니다

2024-10-02 08:44 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
챌린지에서 참여자 목록을 조회할 수 있을텐데, 거기서 간단하게 모달창으로 띄울 만한 정보를 제공하는 목적으로 만들었습니다!

2024-10-02 09:22 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
제가 놓친 부분이 있었네요.. `participation-id`로 참여 정보는 특정할 수 있어서 요청하는 회원이 해당 참여 인원인지 확인하는 로직을 추가했습니다! 감사합니다 ㅎㅎ

[ddf39d1](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/50/commits/ddf39d1ba32087c9674d9f0dd9d2d648f04ccdff) 커밋에 반영했습니다!

2024-10-02 14:46 UTC, kangboom commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
명덕님 지금 response가 `memberId`를 리턴하는데 프론트에서 요청을 하려면 `participantId`를 알아야 되는데 `participantId` 를 받을 수 있는 수단이 없는 것 같아요 . 제가 delete 에서 질문드린 것도 프론트에서 `participantId`를 받을 수 없어서 하는 말이었습니다. 
```
public record ChallengeParticipationMemberResponse(
        Long id,
        String nickname,
        String imageUrl,
        LocalDateTime participatedAt,
        Integer entryFee
) {
```
```
    private ChallengeParticipationMemberResponse toParticipationMemberResponse(ChallengeParticipation challengeParticipation) {
        Member member = challengeParticipation.getMember();
        return new ChallengeParticipationMemberResponse(
                member.getId(),
                member.getNickname(),
                member.getImageUrl(),
                challengeParticipation.getCreatedAt(),
                challengeParticipation.getEntryFee()
        );
    }
```

2024-10-02 14:48 UTC, kangboom commented
명덕님 그리고 branch 들어가 봤는데 코드 최신화가 안되어있는 것 같습니다!

2024-10-03 03:31 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
아 그러네요! 바로 추가하도록 하겠습니다

2024-10-03 03:34 UTC, Profile-exe commented on src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
> +    }
```json
{
  "participationId": 3,
  "memberId": 1,
  "nickname": "김철수",
  "imageUrl": "https://example.com/image1.jpg",
  "participatedAt": "2024-10-03T03:33:18",
  "entryFee": 500
}
```

이렇게 반환되도록 구현했습니다. 해당 내용은 [0621255](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/50/commits/06212554466d4beed5b6d361daeaab7784b74402) 커밋에 반영했습니다!

2024-10-03 03:38 UTC, kangboom approved these changes

2024-10-03 04:55 UTC, Wonmoan approved these changes
챌린지와 챌린지 참여자 간의 매핑이 어려우셨을 것 같은데,  잘 해주신 것 같습니다. 
마찬가지로, 챌린지와 회원 간의 검증 로직과 챌린지에서의 검증까지도 잘 이루어진 것 같습니다.

추가로, 챌린지 참여 시 인증된 사용자의 정보를 가져오는 로직을 따로 분리해두면 더 좋을 것 같습니다!

강범님 께서 말씀하신 `participantId`을 받는 피드백도 반영이 잘 된 것 같아 approve하겠습니다. 고생하셨습니다.

2024-10-03 05:06 UTC, seolbin96 approved these changes
챌린지 파트 어려울 것 같았는데 빠르게 잘해주셨네요🥺 제가 맡은 ArgumentResolver 부분도 얼른 구현해보도록 하겠습니다..! 피드백도 다 반영된 것 같아서 approve 할게요. 수고하셨습니다!!

2024-10-03 05:09 UTC, merged