Feat/17/feed likes create delete
kakao-tech-campus-2nd-step3/Team15_BE pull request #51
Opened 2024-10-03 11:17 UTC by kangboom

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- 좋아요 멤버 조회 구현
- 좋아요 추가 구현
- 좋아요 삭제 구현
- Feed Response Dto에 좋아요 수를 나타내는 likes 필드 추가

## 이슈 링크
close #17

## 참고사항
좋아요를 누른 멤버를 조회하는 기능에 대해서는 얘기해보지 않았지만, 개발하면서 있으면 좋겠다는 생각이 들어 일단 구현해봤습니다! 이 기능에 대해서 어떠신지 이야기 들어보고 싶습니다!

2024-10-03 12:03 UTC, Profile-exe requested changes
깔끔하게 구현해주셨네요! 코드가 읽기 편해서 좋았습니다 😃
좋아요 생성 시 반환되는 `URI`에 대한 코멘트 남겨드렸으니 확인 부탁드려요!

2024-10-03 12:03 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/controller/FeedController.java
> +        return ResponseEntity.created(URI.create("/feeds/likes" + likesId)).build();
`URI` 경로 수정이 필요할 것 같습니다!
```java
String uri = String.format("/feeds/%d/likes/%d", feedId, likesId);
return ResponseEntity.created(URI.create(uri)).build();
```
이렇게 중간에 `feedId`가 들어가는게 일관성 있는 것 같습니다.

2024-10-03 12:42 UTC, kangboom commented on src/main/java/kakao/rebit/feed/controller/FeedController.java
> +        return ResponseEntity.created(URI.create("/feeds/likes" + likesId)).build();
[6f13db5](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/51/commits/6f13db5a349bdce7f7fc85863eeffd824b9883f7): 반영해서 수정했습니다!

2024-10-03 12:43 UTC, Profile-exe approved these changes
빠른 피드백 감사합니다. 수고하셨습니다!

2024-10-04 08:02 UTC, seolbin96 approved these changes
좋아요 누른 멤버 조회하는 기능 좋은 것 같습니다!! 수고하셨습니다

2024-10-04 08:05 UTC, merged