[FEAT] 책 DTO 생성 (best서평, 한줄평 포함)
kakao-tech-campus-2nd-step3/Team15_BE pull request #52
Opened 2024-10-03 11:33 UTC by Wonmoan

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- 출판일자(`pub_date`) 필드 추가되었습니다.
- 표지 이미지 필드명이 기존  `imageUrl` → `cover`로 변경되었습니다.
- isbn 조회 엔드포인트 수정되었습니다. `/{isbn}`
- 책 DTO BookResponse 로 값을 주고 받도록 변경했습니다.
- 알라딘 api  `url` 에 변경이 있습니다
  - `책 제목` 기반 검색과 `isbn`기반 검색의 요청 url이 달라 수정하여 반영되었습니다. 
- `RestClient` 사용해 알라딘 API에 요청을 보내고 처리 하도록 수정되었습니다.
- 알라딘 `ttb_key` .env파일에서 불러오도록 수정하였습니다. 

## 이슈 링크
close #42

## 참고사항
- 책 필드의 추가와 수정의 이유로 강범님 께서 맡아 주신 `Feed` 쪽 수정이 조금 있습니다. 확인해서 리뷰 부탁드리겠습니다.
  - FeedMapper의 `toBookResponse` 부분 주석처리해서 변경사항  표시해놨습니다.]
- dto에 아직 best서평과 한줄평은 담겨있지 않습니다.

2024-10-03 13:32 UTC, Profile-exe requested changes
수고하셨습니다! 코멘트 확인 부탁드립니다.
추가로 불필요한 `import` 구문 및 공백 제거 등 컨벤션도 신경써주시면 좋을 것 같습니다!

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
> +@JsonPropertyOrder({ "id", "isbn", "title", "author", "cover", "description", "publisher", "pubDate" })
해당 어노테이션이 없는 경우, `record`에서 정의한 필드 순서에 따라 반환되지 않고 무작위로 반횐되어서 적용한 것인가요?

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/entity/Book.java
> +    @Column(name = "pub_date")
`JPA`에서 별다른 옵션을 적용하지 않았다면 기본적으로 카멜케이스 필드를 데이터베이스에서 스네이크케이스로 설정해줍니다. 해당 어노테이션 삭제 후 확인 부탁드리고, 만약 어노테이션 삭제 후에도 카멜케이스로 데이터베이스 필드명이 적용된다면 말씀해주시면 감사하겠습니다!

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +            + "&output=js&Version=20131101";
여기 `Version` 파라미터는 개행을 안한 이유가 있을까요?
그리고 `20131101`이면 꽤 오래된 버전인 것 같은데, 다른 최신 정보를 얻는 버전이 따로 있나요?

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +    private static final String ITEM_SEARCH_ENDPOINT = "/ItemSearch.aspx";
변수 선언도 가독성있게 바꾸면 좋을 것 같습니다!
```java
@Value("${TTB_KEY}")
private String TTB_KEY;

private static final String BASE_API_URL = "http://www.aladin.co.kr/ttb/api";
private static final String QUERY_PARAMS_FORMAT = "&QueryType=%s&MaxResults=%s&start=1&SearchTarget=Book&output=js&Version=20131101";

private static final String ITEM_LOOKUP_ENDPOINT = "/ItemLookUp.aspx";
private static final String ITEM_SEARCH_ENDPOINT = "/ItemSearch.aspx";
```

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
불필요한 어노테이션 제거 바랍니다! 디스코드에 PR 제출 전 TODO (import 정리, 포맷팅 등) 올려놓았었는데 해당 부분 확인 부탁드려요

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +
여기만 개행이 두 줄인 것 같네요.

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
> +    private BookResponse convertToBookResponse(Book book) {
메서드명을 `convert~`로 지으셨는데, 다른 도메인과 통일하는게 좋을 것 같습니다! 해당 메서드명이 적절한 것 같다면 다른 분들과 함께 얘기해보면 좋을 것 같습니다.

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
`JPA` 리파지토리를 이용하는데, `@Transactional` 어노테이션이 필요한 메서드들에 적용이 되어있지 않은 것 같습니다!

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
> +            .collect(Collectors.toList());
`stream`에서 `collect(Collectors.toList())`를 사용하시는데, `toList()`를 적용할 수 있을 것 같습니다.
둘 사이의 차이가 무엇인지, 각 상황에서 어떤 메서드를 호출하는게 적절한지 알아보시면 좋을 것 같아요!

2024-10-03 13:32 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
> +
클래스 마지막 빈 줄이 두 개네요. 제거 부탁드립니다.

2024-10-03 13:32 UTC, Profile-exe commented on src/main/resources/application.yml
> +    import: "optional:file:.env"
처음 프로젝트 설정하면서 `.env`를 사용할 수 있도록 했는데 해당 설정을 추가하신 이유가 있으신가요? 제거하고 테스트해보고 안된다면 말씀해주시면 감사하겠습니다!

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
> +@JsonPropertyOrder({ "id", "isbn", "title", "author", "cover", "description", "publisher", "pubDate" })
`record` 에서 정의한 필드 순서로 반환 하긴 합니다. 

수정 전의 필드 순서가 현재와 같지 않아,  값은 제대로 불러오지만 필드명에 매칭되는 값은 아니었습니다. 
필드 순서를 현재와 같이 수정하는 김에, 좀 더 확실하게 하기 위해 해당 어노테이션을 사용했습니다.

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/entity/Book.java
> +    @Column(name = "pub_date")
그렇군요! 
해당 어노테이션 삭제후 데이터베이스 필드명이 스테이크케이스로 설정 됨을 확인 했습니다.
해당 어노테이션 삭제하였습니다! [78dd952](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/78dd9520ae8db7e82d4a4383013b859695e22b9c)

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +            + "&output=js&Version=20131101";
- Version 파라미터 개행 추가하였습니다.  [8f7607f](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/8f7607fc3d325134c97332f4114a711cf501659e)
- 알라딘 OpenAPI의 경우 최종 수정일이 (`2022.7.13`) 으로  `최신버전` : `20131101` `구버전` : `20070901` 으로 제공하고 있습니다.
https://blog.aladin.co.kr/openapi/popup/6695306
https://docs.google.com/document/d/1mX-WxuoGs8Hy-QalhHcvuV17n50uGI2Sg_GHofgiePE/edit

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +    private static final String ITEM_SEARCH_ENDPOINT = "/ItemSearch.aspx";
반영했습니다! [1d6bffa](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/1d6bffa431d7114d7545e142e1f6fc3906945e40)

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
> +    private BookResponse convertToBookResponse(Book book) {
[60bd98c](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/60bd98ca844ebd3ce9cc75e1adf941e8ba23449b)
다른 도메인과 일관성 있게 수정하였습니다.

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
반영했습니다! 확인 한번 부탁드립니다! [e20f5dc](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/e20f5dc61596ee1e8e9d4935f1ef252c33ec7604)

2024-10-03 14:57 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
> +            .collect(Collectors.toList());
`Collectors.toList()` : `ArrayList` 를 반환하여 수정하거나 추가하는 등의 작업 가능 
`Stream.toList()` : 불변 리스트를 반환하며, 결과 리스트는 변경할 수 없다

제가 이해한 바가 맞을까요? 
추후에 `한줄평`이라던지 추가적인 정보들을 담아야 하는 수정 가능성이 있을 것 같아
기존의 `Collectors.toList()`를 유지하는 것이 좋아 보이는데 명덕님은 어떻게 생각하시나요??

2024-10-03 14:57 UTC, Wonmoan commented on src/main/resources/application.yml
> +    import: "optional:file:.env"
[db4047a](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/db4047a559be83dc344eae6a46371623c8d69a1a)
해당 설정 삭제해도 정상 작동하는 것을 확인했습니다
수정해서 반영하였습니다!

2024-10-03 15:00 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
조회 로직에는 적용이 안된 것 같네요! 다른 도메인에 구현된 코드들을 보면서 해보시면 좋을 것 같습니다!

2024-10-03 15:01 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +            + "&output=js&Version=20131101";
그렇군요! 상세하게 알려주셔서 감사합니다!

2024-10-03 15:04 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
> +@JsonPropertyOrder({ "id", "isbn", "title", "author", "cover", "description", "publisher", "pubDate" })
그러면 다른 `DTO`들에도 통일해서 적용 여부를 결정해야 할 것 같은데, 해당 어노테이션을 추가해서 얻는 이점과 이로 인해 발생하는 비용(`DTO` 필드명 수정 등)을 고려했을 때, 원모님은 어떻게 하는게 좋다고 생각하시나요?

2024-10-03 15:13 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
> +            .collect(Collectors.toList());
`한줄평`은 다른 테이블에서 가져오는 정보이며 책 엔티티에 저장되는 정보는 아닙니다. 
`한줄평`과 `BEST 서평` 등은 `책 상세정보 조회` 등의 `API`에서 단일 책을 조회할 때, 책의 정보와 함께 피드 도메인의 리파지토리를 사용해 `DTO`로 묶어서 보내게 됩니다.

따라서 책 목록 조회할 때 `한줄평`, `BEST 서평` 등의 정보를 함께 주는것이 맞는지 고민해 볼 필요가 있습니다.

> 수정 가능성이 있을 것 같아

이 부분에 대해서는 지금은 `toList()`로 변환을 못하게 강제하고, 추후 수정하는 로직이 추가되었을 때, `Collectors.toList()`로 변경하는건 어떨까요? 꼭 필요할 때 변경이 가능하도록 바꿔주는게 더 안전하다고 생각합니다!

2024-10-03 15:48 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
> +@JsonPropertyOrder({ "id", "isbn", "title", "author", "cover", "description", "publisher", "pubDate" })
해당 어노테이션을 붙이지 않아도 아직 까진 정의된 필드 순서에 따라 잘 매칭이 되기에
추후에 매칭이 잘 안된다면 그때 반영해도 좋을 것 같습니다.

2024-10-03 15:48 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
```
@Transactional(readOnly = true)
    public List<BookResponse> getAllBooks() {
        return bookRepository.findAll().stream()
            .map(this::toBookResponse)
            .collect(Collectors.toList());
    }
```
 ```
    @Transactional(readOnly = true)
    public Book findBookByIdOrThrow(Long bookId) {
        return bookRepository.findById(bookId)
            .orElseThrow(() -> new IllegalArgumentException("해당 책이 존재하지 않습니다."));
    }
```
조회시에도 반영했습니다!

2024-10-03 15:49 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
> +            .collect(Collectors.toList());
네 알겠습니다
[f0fc411](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/f0fc411b46d6c33a8dfe91170abdc26ed84d1eff) 반영하였습니다 !

2024-10-03 15:50 UTC, kangboom approved these changes
고생하셨습니다~~

2024-10-03 15:50 UTC, kangboom commented on src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
> +            book.getPublisher(),
저는 피드에서만 사용되는 BookResponse를 의도하고 만든 건데, Book 도메인 만의 Response를 따로 만드는 건 어떻게 생각하시나요? 책이 사용되는 곳이 책 상세 페이지, 독서 일기, 피드 만들 때 책 선택하기 등이 있을텐데 각 기능마다 필요한 데이터가 다를 수 있고 추후에 영역 별로 기능이 추가/수정된다고 하면 분리해서 개발하는 게 좋을 것 같은데 어떻게 생각하시나요?

2024-10-03 15:50 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +        System.out.println("API에서 받은 책 정보: " + bookResponse);
이 부분은 삭제해야 될 것 같습니다!

2024-10-03 15:50 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/BookService.java
> +        );
지금 Feed 도메인의 BookResponse를 사용하고 있는데 만약 `Feed`도메인과 BookResponse를 공유한다면  `FeedMapper` 의 `toBookResponse`을 public 으로 열고 사용하면 중복을 줄일 수 있을 것 같습니다!

2024-10-03 15:50 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
Isbn으로 찾으면 항상 단일 인스턴스가 나올텐데 `map`을 사용하면 인스턴스가 여러 개가 나오는 느낌을 받아서요.. `map`을 사용하신 이유가 있으신가요? 그리고 이건 그냥 스타일 문제 같은데 이런 식의 코드는 어떠신가요?
```
public BookResponse getBookDetail(String isbn) {
    Book book = bookRepository.findByIsbn(isbn).orElseGet(() -> searchAndSaveBookByIsbn(isbn));
    return toBookResponse(book);
}
```

2024-10-03 15:57 UTC, kangboom requested changes

2024-10-03 15:57 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +        System.out.println("API에서 받은 책 정보: " + bookResponse);
이 부분은 삭제해야 될 것 같습니다!

2024-10-03 15:57 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
Isbn으로 찾으면 항상 단일 인스턴스가 나올텐데 `map`을 사용하면 인스턴스가 여러 개가 나오는 느낌을 받아서요.. `map`을 사용하신 이유가 있으신가요? 그리고 이건 그냥 스타일 문제 같은데 이런 식의 코드는 어떠신가요?
```
public BookResponse getBookDetail(String isbn) {
    Book book = bookRepository.findByIsbn(isbn).orElseGet(() -> searchAndSaveBookByIsbn(isbn));
    return toBookResponse(book);
}
```

2024-10-03 15:57 UTC, kangboom commented on src/main/java/kakao/rebit/book/service/BookService.java
> +        );
지금 Feed 도메인의 BookResponse를 사용하고 있는데 만약 Feed도메인과 BookResponse를 공유한다면 FeedMapper 의 toBookResponse을 public 으로 열고 사용하면 중복을 줄일 수 있을 것 같습니다!

2024-10-03 15:57 UTC, kangboom commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
저는 피드에서만 사용되는 BookResponse를 의도하고 만든 건데, Book 도메인 만의 Response를 따로 만드는 건 어떻게 생각하시나요? 책이 사용되는 곳이 책 상세 페이지, 독서 일기, 피드 만들 때 책 선택하기 등이 있을텐데 각 기능마다 필요한 데이터가 다를 수 있고 추후에 영역 별로 기능이 추가/수정된다고 하면 분리해서 개발하는 게 좋을 것 같은데 어떻게 생각하시나요?

2024-10-04 03:23 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/AladinApiService.java
> +        System.out.println("API에서 받은 책 정보: " + bookResponse);
[ca7a558](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/ca7a558a1a81d2b63e9eda0070fd858eca74d2a8)
불필요한 로그 삭제하였습니다!

2024-10-04 03:24 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
map 메서드는 스트림이나 컬렉션에서 여러 값을 처리할 때 주로 사용되기 때문에, 여기에 map을 사용하면 많은 값을 다루는 것으로 오해한다는 말씀이실까요? 

findByIsbn(isbn)이 반환하는 값은 Optional<Book>으로
Optional의 값을 변환해서 사용해야 하는 경우, map()을 이용해 기존 값을 변환하여 값을 가져오기에 
가능하다면 기존의 방식을 유지하고 싶습니다.

2024-10-04 03:24 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
> +        );
다음 step에서 bookresponse 따로 분리해서 작업 하겠습니다!

2024-10-04 03:24 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
Book 도메인 만의 Response를 따로 만드는게 좋을 것 같습니다. 

출판일자(`pub_date`) 필드의 추가와 표지 이미지 필드명이 기존 `imageUrl` → `cover`로 변경 되어 
다음 작업 하실 때 feedmapper 쪽 확인 한번 후 작업 부탁드립니다. 

다음 step에서 bookresponse 따로 분리해두겠습니다.

2024-10-04 04:33 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
`map` 사용은 당연하고 자연스러운거라 생각하는데, `map`을 사용하여 인스턴스가 여러 개 나온다는 느낌은 `stream`을 사용할 때 자주 접하셔서 그런 것 같습니다! 저도 기존 방식을 유지하는게 좋다 생각합니다.

2024-10-04 04:36 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
하지만, `findByIsbn` 메서드를 재사용할 수 있으므로, `findByIsbnOrThrow`로 메서드로 추출해서 사용하는것도 다른 도메인 코드들처럼 일관성 있는 느낌이라 좋을 것 같습니다!
```java
// ...
    Book book = findByIsbnOrThrow(isbn);
    return toBookResponse(book);
}


private Book findByIsbnOrThrow(String isbn) {
    bookRepository.findByIsbn(isbn).orElseGet(() -> searchAndSaveBookByIsbn(isbn));
}
```

2024-10-04 11:48 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
1번방식
```
    @Transactional
    public BookResponse searchAndSaveBookByIsbn(String isbn) {
        AladinApiResponseResponse bookResponse = aladinApiService.searchBookByIsbn(isbn);
        Book book = bookRepository.findByIsbn(bookResponse.isbn())
            .orElseGet(() -> saveBook(bookResponse));
        return BookMapper.toBookResponse(book);
    }

    @Transactional
    public BookResponse getBookDetail(String isbn) {
        return bookRepository.findByIsbn(isbn)
            .map(BookMapper::toBookResponse)
            .orElseGet(() -> searchAndSaveBookByIsbn(isbn));
    }
```
2번방식
```
    @Transactional
    public Book searchAndSaveBookByIsbn(String isbn) {
        AladinApiResponseResponse bookResponse = aladinApiService.searchBookByIsbn(isbn);
        return bookRepository.findByIsbn(bookResponse.isbn())
            .orElseGet(() -> saveBook(bookResponse));
    }

    @Transactional
    public BookResponse getBookDetail(String isbn) {
        Book book = findByIsbnOrThrow(isbn);
        return BookMapper.toBookResponse(book);
    }

    @Transactional
    private Book findByIsbnOrThrow(String isbn) {
        return bookRepository.findByIsbn(isbn)
            .orElseGet(() -> searchAndSaveBookByIsbn(isbn));
    }
```
1번방식과 2번방식 중 고민이 됩니다 

1번방식 :  `BookResponse`를 반환하기 때문에, `BookResponse`가 필요한 경우 중간 변환 없이 바로 사용 가능
2번방식 : 매서드 재사용에 용의하지만 `book` 을 반환 `BookResponse` 책 검색 방식(제목,isbn)에 따라 isbn 검색 시 엔티티 책 제목 검색시 DTO가 반환

의견을 여쭙고 싶습니다.

2024-10-04 11:48 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
[d49f82b](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/d49f82b81bb6f95f1d08afad65c9b31e32201953)
이름을 그대로 `BookResponse` 로 두고 import 시 feed패키지의 `BookResponse` 인지 book패키지인지 유의해서 가져 오는 방식이 좋을까요? 아니면 `BookDetailResponse` 등으로 차이를 주는게 좋을까요?  현재는 앞의 방식을 사용했습니다.

2024-10-04 11:59 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
저는 큰 문제가 없다면 현재 방식도 괜찮다 생각합니다! 아니면 피드 도메인의 경우 앞에 명시해서 `FeedBookResponse`도 괜찮은 것 같아요

2024-10-04 12:02 UTC, kangboom commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
저도 `FeedBookResponse`가 좋을 것 같습니다! 제 부분이긴 하지만 이 PR에서 수정해주실 수 있으실까요??

2024-10-04 12:02 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
네이밍만 수정하면 될까요?

2024-10-04 12:04 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
네 `Refactor -> rename (shift + F6)`으로 해당 객체의 네이밍만 변경해도 좋을 것 같습니다.

2024-10-04 12:04 UTC, Wonmoan commented on src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
>  }
넵

2024-10-04 12:11 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
- `private` 메서드에 `@Transactional` 어노테이션을 적용하셨는데, 아래와 같은 경고문구가 안떠서 이대로 구현하신건지 궁금합니다! `private` 메서드들은 `AOP`가 적용되지 않습니다. 경고문구 확인 부탁드려요!

![image](https://github.com/user-attachments/assets/71544bcd-5554-4de1-8d60-c7a529058254)
- 추가로 중복되는 로직이 있는 것 같은데, 불필요한 로직은 과감히 삭제하는게 낫다고 봅니다. 두 번째 방식에서 `findByIsbnOrThrow`인데 예외를 던지지도 않아서요. 

- 그리고 `@Transactional` 어노테이션을 `readOnly` 등의 옵션 없이 모든 메서드에 붙이신 것 같은데, `@Transactional` 어노테이션 사용 방법과 트랜잭션 전파(propagation)을 알아보시고 올바르게 적용하시는게 좋을 것 같습니다! GPT한테 이렇게 어노테이션과 접근지정자를 적용하는게 괜찮은지 먼저 물어보는 것도 좋습니다.

아래 코드처럼 개선이 가능할 것 같은데, 원모님 의견이 궁금합니다!

```java
@Transactional
public BookResponse getBookDetail(String isbn) {
    Book book = searchAndSaveBookByIsbn(isbn);
    return BookMapper.toBookResponse(book);
}

private Book searchAndSaveBookByIsbn(String isbn) {
    AladinApiResponseResponse bookResponse = aladinApiService.searchBookByIsbn(isbn);
    return bookRepository.findByIsbn(bookResponse.isbn())
        .orElseGet(() -> saveBook(bookResponse));
}

private Book saveBook(AladinApiResponseResponse bookResponse) {
    return bookRepository.save(BookMapper.toBookEntity(bookResponse));
}
```

2024-10-04 13:51 UTC, kangboom approved these changes

2024-10-04 13:58 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
[81171d8](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/81171d8bfd71eba5bc180b43894cc5fcb06f65ff) 
수정 사항 반영했습니다.
- isbn검색도 제목 조회와 같이 public으로 접근지정자 수정하고 `@Transactional` 반영했습니다. 
- `searchAndSaveBookByIsbn` 조언 해주신 대로 수정하였습니다.

2024-10-04 14:03 UTC, Profile-exe commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
`searchAndSaveBookByIsbn` 접근제어자가 `public`이고 `@Transactional` 어노테이션도 아직 있는 것 같은데, 이유가 있을까요?

- 우선 `searchAndSaveBookByIsbn` 메서드는 동일한 클래스 내의 `getBookDetail`에서만 사용되며, 이는 `private`가 적절하다 생각합니다.
- 또한 앞서 언급드렸듯 "트랜잭션 전파"를 고려해서 해당 메서드에는 `@Transactional` 어노테이션이 불필요한 상황입니다.

제가 조언드린대로 코드를 수정하셨다고 했는데, 제 코드랑 다른 점들이 있어서 왜 이렇게 구현하셨는지 궁금합니다!

2024-10-04 14:28 UTC, Wonmoan commented on src/main/java/kakao/rebit/book/service/BookService.java
>      }
외부에서 `isbn`검색시 사용 된다고 잠시 혼동했습니다. 
이미 isbn 검색 조회시는  `getBookDetail` 를 통해 외부에서 호출되고 `searchAndSaveBookByIsbn`는 같은 클래스내의 `getBookDetail`  에만 사용되고 있는 있고,
 `getBookDetail`에 `@Transactional` 어노테이션이 사용됨 으로 `searchAndSaveBookByIsbn`는 사용될 필요 없고요 (private 이기도 하고 )
착각했습니다 수정사항 반영 했습니다. [893694e](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/52/commits/893694e2b5bef53fa2359eacbcb8c885f8ae3170)

2024-10-04 14:30 UTC, merged