[REFACTOR] 피드 업데이트 리팩토
kakao-tech-campus-2nd-step3/Team15_BE pull request #92
Opened 2024-10-12 15:14 UTC by kangboom

## PR 유형
- [x] 기능 추가
- [x] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
- FavoriteBook 업데이트 API 작성
- Magazine 업데이트 API 작성
- Story 업데이트 API 작성

## 이슈 링크
close #91

2024-10-13 11:37 UTC, Profile-exe requested changes
수고하셨습니다! 코멘트 남겼으니 확인 부탁드려요

2024-10-13 11:37 UTC, Profile-exe commented on src/main/java/kakao/rebit/common/domain/ImageKeyHolder.java
> +    }
메서드명과 그 내용 간의 차이가 존재하는 것 같습니다. 다음과 같이 바꿔보는것은 어떨까요?
```java
default boolean isImageKeyChanged(String newImageKey) {
    return !this.getImageKey().equals(newImageKey);
}
```

```java
// 이미지가 수정됐으면 기존의 S3에서 이전 이미지 삭제하기
if (magazine.isImageKeyChanged(updateRequest.imageKey())) {
    s3Service.deleteObject(magazine.getImageKey());
    magazine.changeImageKey(updateRequest.imageKey());
}
```

2024-10-13 11:37 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/controller/FeedController.java
> +            MagazineResponse.class, StoryResponse.class})))
이런건 보기 좋게 한 줄로 놓아도 좋을 것 같습니다. intelliJ의 줄바꿈 기준이 각자 달라서 이런 현상이 생기는 것 같네요

2024-10-13 11:37 UTC, Profile-exe commented on src/main/java/kakao/rebit/s3/service/S3Service.java
> +            "gif", "svg", "webp");
여기도 마찬가지입니다. 줄바꿈을 해서 더 가독성이 안좋아지는 것 같아요

2024-10-13 11:37 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/controller/MagazineController.java
> +    }
`Swagger`에는 목록을 조회하는 경우 `@ApiResponse`로 해결되지 않을 것이라 생각합니다. 단일값만 어노테이션으로 해결하셨는데, 제가 디스코드에서 말씀드린 것처럼 근본적으로 해결하시는게 더욱 좋을 것 같습니다.

2024-10-14 10:17 UTC, kangboom commented on src/main/java/kakao/rebit/common/domain/ImageKeyHolder.java
> +    }
[747330b](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/92/commits/747330b3c91c98ad5453caea64116c6d048c17f4): 반영했습니다.

2024-10-14 10:18 UTC, kangboom commented on src/main/java/kakao/rebit/feed/controller/FeedController.java
> +            MagazineResponse.class, StoryResponse.class})))
[5ac02f8](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/92/commits/5ac02f84a99d120923b4fbe84bd8b4a12bded13f): 반영했습니다.

2024-10-14 10:18 UTC, kangboom commented on src/main/java/kakao/rebit/s3/service/S3Service.java
> +            "gif", "svg", "webp");
[5ac02f8](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/92/commits/5ac02f84a99d120923b4fbe84bd8b4a12bded13f): 반영했습니다.

2024-10-14 10:18 UTC, kangboom commented on src/main/java/kakao/rebit/feed/controller/MagazineController.java
> +    }
[8d67aeb](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/92/commits/8d67aeb90801eb4fdfc0965ce464c193d22e4a00)
[4f3fb98](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/92/commits/4f3fb984ce28673c0fbfd486ce4fe024c9dd6866)
반영했습니다.

2024-10-14 10:24 UTC, Profile-exe approved these changes

2024-10-14 12:01 UTC, merged