[FEAT] 도메인 별 S3 이미지 업로드 및 조회 구현
kakao-tech-campus-2nd-step3/Team15_BE pull request #96
Opened 2024-10-17 08:15 UTC by kangboom

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
작업 내용 및 변경사항 작성

## 이슈 링크
close #93

## 참고사항
<html>
<body>
<h2>ImageKey를 위한 인터페이스 추가</h2>
<ul>
<li>ImageKeyAccessor: 조회만 가능한 클래스에 사용
<ul>
<li>챌린지</li>
<li>챌린지 인증글</li>
</ul>
</li>
<li>ImageKeyModifier: 조회, 수정까지 가능한 클래스에 사용
<ul>
<li>피드</li>
<li>멤버</li>
</ul>
</li>
</ul>
<h2>ImageKey 검증 패턴</h2>
<pre><code class="language-java">String BASE_IMAGE_KEY_FORMAT = &quot;/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/[^/]+$&quot;;
</code></pre>
<p>검증 패턴: <code>@Pattern(regexp =“^domain” + BASE_IMAGE_KEY_FORMAT)</code></p>
<h2>트랜잭션을 고려한 업로드 / 삭제 로직 수정</h2>
<p><strong>피드 삭제 코드</strong></p>
<pre><code class="language-java">feedRepository.deleteById(feedId);

// 메거진과 스토리는 피드 삭제 전 S3에서 image 파일을 먼저 삭제한다.
if (feed instanceof ImageKeyAccessor imageKeyAccessor) {
3Service.deleteObject(imageKeyAccessor.getImageKey());
}
</code></pre>
<ul>
<li>DB에 먼저 삭제 후, S3에 삭제 → 이런 식으로 구현하면 DB에서 에러가 날 경우도 롤백, S3에서 삭제가 실패할 경우도 Error가 전달돼서 롤백 가능</li>
<li>만약 S3에서 삭제를 먼저 하게 되면, DB에 삭제가 실패했음에도 S3에는 사진이 삭제될 수 도 있음.</li>
</ul>
<h2>공통</h2>
<ul>
<li>request Dto: <code>imageUrl</code>→ <code>ImageKey</code> 변경</li>
<li>response Dto: <code>imageUrl</code>→ <code>ImageKey</code> 변경 및 사진을 받기 위한 <code>presignedUrl</code>필드 추가</li>
</ul>
<h2>Challenge</h2>
<ul>
<li>
<p>XXXservice: <code>toXXXResponse</code> 로 변환할 때, <code>S3Service</code>에서 download presignedUrl 받도록 수정</p>
</li>
<li>
<p>챌린지 삭제 시 S3에 저장된 기존 이미지 삭제</p>
<pre><code class="language-java">// S3에 저장된 이미지 삭제
s3Service.deleteObject(challenge.getImageKey());
</code></pre>
</li>
<li>
<p>챌린지 삭제 오류 수정</p>
<pre><code class="language-java">// 기존 코드 -&gt; 삭제가 가능하면 오류 발생
if (challenge.canBeDeleted(LocalDateTime.now())) {
    throw DeleteNotAllowedException.EXCEPTION;
}

// 수정된 코드 -&gt; 삭제가 불가능할 경우 오류 발생
if (!challenge.canBeDeleted(LocalDateTime.now())) {
    throw DeleteNotAllowedException.EXCEPTION;
}
</code></pre>
</li>
</ul>
<h2>Member</h2>
<ul>
<li>MemberResponse: <code>imageUrl</code> → <code>ImageKey</code> 변경</li>
<li>멤버 정보 조회를 위한 <code>MemberProfileResponse</code>  DTO 생성
<ul>
<li>S3 presignedUrl 이 필요한 응답에 사용</li>
</ul>
</li>
<li>멤버 이미지 수정 시, S3에 저장된 이미지 삭제</li>
<li>멤버 삭제 시, S3에 저장된 이미지 삭제</li>
</ul>
<h2>Auth</h2>
<ul>
<li>카카오에서 사용자 정보 불러올 때, 프로필 이미지 url도 함께 가져오도록 수정
<ul>
<li><a href="http://KakaoUserInfo.Properties">KakaoUserInfo.Properties</a> → profile_image 필드 추가</li>
</ul>
</li>
<li><code>findOrCreateMemberByEmail</code> 에서 사용자 정보가 없을 경우(최초 로그인일 경우), 카카오 프로필 이미지 Url에서 이미지를 다운 받은 후 S3에 저장</li>
</ul>
<h2>S3</h2>
<h3>Enum</h3>
<ul>
<li>S3에 저장할 이미지를 도메인 별로 분류하기 위해 type 값 생성</li>
</ul>
<h3>Dto</h3>
<ul>
<li>FileInfo : 파일 이름과 확장자를 가지고 있는 Dto</li>
<li>DownloadImageInfo: 이미지 byte 배열을 가지고 있는 Dto, imageUrl로부터 이미지를 다운 받은 뒤 byte[] 형태로 저장</li>
<li>S3UploadKeyRequest
<ul>
<li>S3ObjectRequest를 만드는 데 필요한 imageKey와 contentType을 가지고 있는 dto</li>
</ul>
</li>
</ul>
<h2>Util 클래스 생성</h2>
<ul>
<li>ImageDownloader: 이미지를 추출해서 반환 하는 로직 → @Bean으로 설정 의존성 주입 받아 사용, RestClient 사용
<ul>
<li>이미지 다운로드 예외 처리 구현 :
<code>common.exception.ImageErrorCode</code> , <code>common.exception.ImageDownloadErrorException</code></li>
</ul>
</li>
<li>FileUtil: 파일 이름 추출 등 단순한 변환 로직 → Static 메서드 사용</li>
</ul>
<h2>S3 업로드 변경사항</h2>
<ul>
<li>도메인 별로 S3에 저장할 이미지 위치를 구별해주기 위해, upload를 위한 presigned Url 발급 요청 시, type 쿼리 파리미터 추가
<ul>
<li>
<p>이전 쿼리 파라미터</p>

속성 | 값
-- | --
filename | “확장자를 포함한 파일 이름”

<ul>
<li>FEED</li>
<li>CHALLENGE</li>
<li>CHALLENGE_VERIFICATION</li>
</ul>
<p>이 중 하나 |</p>
</li>
</ul>
</li>
</ul>

</body>
</html>

2024-10-17 11:20 UTC, Profile-exe requested changes
수고하셨습니다! 잘못된 비즈니스 로직도 수정해주셔서 감사드립니다.
코멘트 남겨드렸으니 확인 부탁드려요

2024-10-17 11:20 UTC, Profile-exe commented on src/main/java/kakao/rebit/feed/service/FeedService.java
>          // 메거진과 스토리는 피드 삭제 전 S3에서 image 파일을 먼저 삭제한다.
주석 내용도 헷갈리지 않게 함께 수정해야될 것 같습니다!

2024-10-17 11:20 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/dto/KakaoUserInfo.java
> +            String profile_image
컨벤션 지켜주세요! `
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)`을 동일한 파일 내에서 적용하고있는데 이걸 사용하는게 좋을 것 같습니다

2024-10-17 11:20 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
> +    }
이 메서드에서 제공하는 기능들은 `S3Service`에서 책임져야할 내용인 것 같은데, 강범님 생각은 어떠신가요? 

`S3Service`를 주입받는 상황이라 `S3` 관련 로직들은 `S3Service`에 `public`으로 구현해서 호출하면 좋지 않나 싶어서요

2024-10-17 11:20 UTC, Profile-exe commented on src/main/java/kakao/rebit/member/dto/MemberResponse.java
> +    String imageKey,
`DTO`중에서 `imageKey`만 반환하는 곳이랑, `presignedUrl`을 `imageKey`와 함께 반환하는 곳이 있던데, 그 이유가 무엇인가요?

어떤 `DTO`든 `presignedUrl`만 반환해주면 되지 않을까 생각했는데, 이렇게 `presigendUrl` 없이 `imageKey`만 주거나 `presignedUrl`과 함께 `imageKey`를 응답하는 `DTO`가 존재하는 이유가 무엇인지 궁금합니다!

2024-10-17 11:20 UTC, Profile-exe commented on src/main/java/kakao/rebit/s3/service/S3Service.java
> +        s3UploadFileInfo.validUploadImageFileFormat(); // 확장자를 이용해 사용 가능한 이미지 형식인지 검증
사용 가능한 이미지 형식인지 검증하는것은 생성 시점에 수행하는게 적절할 것 같습니다!

- `KakaoAuthService`에서는 깜빡하신건진 모르겠지만 검증을 위한 메서드를 호출하지 않고있습니다. 이렇게 검증 로직을 별도로 둔 경우 호출을 깜빡하는 상황이 생길 수 있습니다.

```java
private S3UploadKeyRequest createS3UploadKeyRequestFromUrl(String imageUrl) {
    S3UploadFileInfo s3UploadFileInfo = S3UploadFileInfo.from(FileUtil.getFilenameFromUrl(imageUrl));
    return S3UploadKeyRequest.from(S3Type.MEMBER, s3UploadFileInfo);
}
```

여기서는 `valid~` 라고 검증 메서드를 호출하고 있고요.

로직을 쭉 살펴보니 `S3UploadFileInfo` 객체를 생성할 때 검증하는게 맞다고 생각하는데, 

```java
public record S3UploadFileInfo(
        String filename,
        String extension
) {

    private static final List<String> ALLOWED_FILE_FORMAT = Arrays.asList("jpg", "jpeg", "png", "gif", "svg", "webp");

    public S3UploadFileInfo {
        validUploadImageFileFormat(extension);
    }

    private void validUploadImageFileFormat(String extension) {
        if (!ALLOWED_FILE_FORMAT.contains(extension)) {
            throw S3NotAllowedFileFormatException.EXCEPTION;
        }
    }

    public static S3UploadFileInfo from(String fullFileName) {
        return new S3UploadFileInfo(
                FileUtil.extractFilename(fullFileName),
                FileUtil.extractExtension(fullFileName)
        );
    }
}
```

이렇게 생성자에서 검증 로직을 수행하게 하면 응집도도 높아지고 검증을 위한 메서드를 따로 호출해야 하는 수고도 덜 수 있을 것 같습니다.

제가 챌린지 참여 검증로직을 수정하면서 제안드린 내용처럼 구현했는데요, [저번주 리뷰 PR](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/90#discussion_r1798198445)에서 멘토님도 언급해주셨어서 참고하시면 좋을 것 같습니다!

2024-10-17 11:20 UTC, Profile-exe commented on src/main/java/kakao/rebit/s3/service/S3Service.java
> +        s3UploadFileInfo.validUploadImageFileFormat(); // 확장자를 이용해 사용 가능한 이미지 형식인지 검증
이렇게 개선했을 때의 각 메서드들의 접근제어자(`private`, `public`)도 확인 부탁드립니다.
참고로 정적 팩토리 메서드를 사용하는 경우 생성자를 `private`으로 해도 좋지만, `record`는 그렇게 하면 동작이 되지 않아 `public`으로 두었습니다.

2024-10-17 13:50 UTC, kangboom commented on src/main/java/kakao/rebit/member/dto/MemberResponse.java
> +    String imageKey,
1. DTO중에서 imageKey만 반환하는 곳이랑, presignedUrl을 imageKey와 함께 반환하는 곳이 있던데, 그 이유가 무엇인가요?
: 실제로 이미지를 사용하는 곳에는 `presignedUrl`을 추가해서 반환하고, 그렇지 않은 곳에는 `imageKey`만 반환하도록 구현했습니다. 예를 들어, MemberResponse는 저희가 resolver를 통해 Member 정보를 받아올 때 사용하는 DTO인데, 이 경우에는 `presignedUrl`을 발급할 필요가 없습니다. 또한, S3에서 `presignedUrl`을 발급받는 과정 자체가 오버헤드가 발생하기 때문에, 불필요한 부분은 최대한 제거하는 것이 성능 측면에서 더 낫다고 생각했습니다.

3.  어떤 DTO든 presignedUrl만 반환해주면 되지 않을까 생각했는데,
: 처음에는 저도 `presignedUrl`만 반환하도록 구현했습니다. 하지만 업데이트 요청 시에 수정 사항이 없는 필드는 기존 값으로 채워서 요청하기 때문에 이럴 경우 기존 값을 프론트에서 알아야 되므로 `imageKey`를 추가했습니다. Challenge 관련 도메인들은 수정이 없기 때문에 `presginedUrl`만 반환해도 되지만 나중에 기능 확장과 API 통일성을 고려해서 `imageKey`를 반환하도록 했습니다.
이 부분에 대해서는 어떻게 생각하시나요??

2024-10-17 14:36 UTC, kangboom commented on src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
> +    }
우선 저는 현재 `downloadImageAndUploadS3` 메서드는 좋은 설계가 아니라고 생각합니다.
왜냐하면 `downloadImageAndUploadS3`는 2가지 책임을 맡고 있습니다. 
1.  url에서 이미지를 다운 받기
2.  다운 받은 이미지를 S3에 저장하기

각 역할이 다른 외부 API를 사용하고 있어 비중이 크기 때문에 이럴 경우는 책임을 분리하는 게 좋다고 생각합니다. 
-> 이미지 다운로드는 `imageDownloader`에서 S3 업로드는 `S3Service`에서 제공
 
그럼에도 불구하고 제가 이렇게 메서드를 작성한 이유는 오로지 가독성 때문입니다.
처음에는 이렇게 구성했습니다.
```java
    private Member createNewMember(KakaoUserInfo userInfo, String accessToken) {
        // 사용자 정보를 바탕으로 새로운 회원 생성
        String nickname = userInfo.properties().nickname();
        String profileImageUrl = userInfo.properties().profileImage();
        String email = userInfo.kakaoAccount().email();

        S3UploadFileInfo s3UploadFileInfo = S3UploadFileInfo.from(FileUtil.getFilenameFromUrl(profileImageUrl)); //url로 부터 파일 정보 가져오기
        S3UploadKeyRequest s3UploadKeyRequest = S3UploadKeyRequest.from(S3Type.MEMBER, s3UploadFileInfo); // S3 업로드를 위한 KeyRequest 만들기

        Member newMember = memberRepository.save(
                Member.init(nickname, s3UploadKeyRequest.imageKey(), email, accessToken)); // 새로운 멤버 생성 후 저장

        DownloadImageInfo downloadImageInfo = imageDownloader.downloadImageFromUrl(imageUrl); // 프로필 이미지 다운
        s3Service.putObject(s3UploadKeyRequest, downloadImageInfo); // s3 저장

        return newMember;
    }
```
이렇게 작성하니 비슷한 내용들끼리 묶어서 메서드로 만들면 훨씬 보기 편하겠다고 생각했습니다. 이로 인해 메서드가 단일 책임 원칙은 지키지 못하지만 private로 `AuthSerivce`에서만 사용되도록 하면 크게 문제가 안될 것 같다고 생각했습니다. 

제 생각에 대한 명덕님 의견 듣고 싶습니다!

2024-10-17 15:00 UTC, kangboom commented on src/main/java/kakao/rebit/feed/service/FeedService.java
>          // 메거진과 스토리는 피드 삭제 전 S3에서 image 파일을 먼저 삭제한다.
[710012c](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/710012c24b6d59ecc625248d1e7b6110d861080b): 반영했습니다.

2024-10-17 15:00 UTC, kangboom commented on src/main/java/kakao/rebit/auth/dto/KakaoUserInfo.java
> +            String profile_image
[a84ce5a](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/a84ce5a10e235176cd11a3b482b9da4d705e95a0): 반영했습니다!

2024-10-17 15:01 UTC, kangboom commented on src/main/java/kakao/rebit/s3/service/S3Service.java
> +        s3UploadFileInfo.validUploadImageFileFormat(); // 확장자를 이용해 사용 가능한 이미지 형식인지 검증
`KakaoAuthService`는 깜빡했습니다.. 명덕님이 알려주신 방법대로 하니 이런 사고도 예방할 수 있고 좋은 것 같습니다. 감사합니다~
[4d5f2f5](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/4d5f2f5b6be5e56f261865cab4818627bd92989a): 반영했습니다,

2024-10-18 07:34 UTC, Profile-exe commented on src/main/java/kakao/rebit/member/dto/MemberResponse.java
> +    String imageKey,
1. `MemberResponse`는 `MemberController`에서 회원정보를 응답하는 용도로 사용중이기 때문에 `presignedUrl`이 필요하다 생각합니다. 따라서 다음 두 방식 중 하나를 고려해보면 좋을 것 같습니다!

    1) `ArgumentResolver`에서 `memberId`만 추출해서 `Long`으로 반환
    2) `MemberResponse`가 아닌 `ArgumentResolver`에서 사용하는 별도의 `DTO` 반환

    불필요한 곳에서는 `presigendUrl`을 반환하지 않아 오버헤드를 줄인다는 것 동의합니다!

3. `PUT` 방식이므로 이렇게 구현하는 것이 적절하겠네요! `Challenge` 도메인도 지금 처럼 `imageKey`까지 넘겨주어도 괜찮을 것 같습니다.

2024-10-18 07:51 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
> +    }
### createS3UploadKeyRequestFromUrl

우선 `createS3UploadKeyRequestFromUrl`부터 말씀드리자면, 현재 로직은 `S3UploadFileInfo` -> `S3UploadKeyRequest` 가 하나의 통일된 로직으로 동작하고있습니다.

따라서 `S3Service`에서 해당 메서드를 `public`으로 두고 재사용하면 어떨까 싶습니다.

- `KakaoAuthService`
```java
private Member createNewMember(KakaoUserInfo userInfo, String accessToken) {
    // ...

    // imageUrl로부터 imageKey 및 contentType 획득
    S3UploadKeyRequest s3UploadKeyRequest = s3Service.createS3UploadKeyRequestFromTypeAndUrl(S3Type.MEMBER, profileImageUrl);

    // ...
}
```

- `S3Service`
```java
public S3UploadUrlResponse getUploadUrl(S3Type type, String fullFilename) {
    S3UploadKeyRequest s3UploadUrlRequest = createS3UploadKeyRequestFromTypeAndUrl(type, fullFilename);

    // ...
}

public S3UploadKeyRequest createS3UploadKeyRequestFromTypeAndUrl(S3Type type, String imageUrl) {
    S3UploadFileInfo s3UploadFileInfo = S3UploadFileInfo.from(FileUtil.getFilenameFromUrl(imageUrl));
    return S3UploadKeyRequest.from(type, s3UploadFileInfo);
}
```

### downloadImageAndUploadS3
이 메서드는 여기에 있어도 될 것 같습니다! 저는 이대로 가도 괜찮다고 생각합니다. 

아래 메서드에서 로직 순서와 함수 식별자를 좀 수정해보았습니다. 
`downloadImageAndUploadS3` -> `downloadProfileImageAndUploadS3`
```java
private Member createNewMember(KakaoUserInfo userInfo, String accessToken) {
    // 사용자 정보를 바탕으로 새로운 회원 생성
    String nickname = userInfo.properties().nickname();
    String profileImageUrl = userInfo.properties().profile_image();
    String email = userInfo.kakaoAccount().email();

    // imageUrl로부터 imageKey 및 contentType 획득
    S3UploadKeyRequest s3UploadKeyRequest = s3Service.createS3UploadKeyRequestFromTypeAndUrl(S3Type.MEMBER, profileImageUrl);

    // 카카오 프로필 이미지 다운 후 S3에 업로드
    downloadProfileImageAndUploadS3(profileImageUrl, s3UploadKeyRequest);

    // 새로운 멤버 생성 후 저장
    Member newMember = Member.init(nickname, s3UploadKeyRequest.imageKey(), email, accessToken);
    return memberRepository.save(newMember);
}

private void downloadProfileImageAndUploadS3(String profileImageUrl, S3UploadKeyRequest s3UploadKeyRequest) {
    DownloadImageInfo downloadImageInfo = imageDownloader.downloadImageFromUrl(profileImageUrl); // imageUrl로부터 이미지 가져오기
    s3Service.putObject(s3UploadKeyRequest, downloadImageInfo); // S3에 저장
}
```

2024-10-19 08:40 UTC, kangboom commented on src/main/java/kakao/rebit/member/dto/MemberResponse.java
> +    String imageKey,
[0dfab3a](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/0dfab3a1e7bad3ab30f19f5fe9843f4f4f180af2)
[62eccaf](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/62eccaf8322e6c78809311ba4a9d75f931bdc84f)

Resolver에서 `MemberResponse` 그대로 사용하고 사진 조회가 필요한 요청은 `MemberProfileResponse`이 반환 되도록 수정했습니다.

[f9dbd91](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/f9dbd911953a56f58ecd01863764c3181294856d)
[cda630b](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/cda630b90c5377861d8ac33b3511eee01ccd0d4e)
리팩토링 과정에서 인터셉트와 리졸버도 수정해봤는데 확인 부탁드려요~

2024-10-19 08:43 UTC, kangboom commented on src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
> +    }
[f8439c8](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/f8439c81746343ab1fa096e53c477d956b660496): 반영했습니다.

`getUploadUrl`에서 `S3UploadKeyRequest`를 생성할 때는 파일이름을 사용하기 때문에 `createS3UploadKeyRequestFromTypeAndUrl` 보다는 `createS3UploadKeyRequestFromTypeAndFilename` 이 적절할 것 같아서 메서드명 수정했습니다.

로직 순서는 트랜잭션과 롤백을 고려해서 일부러 `downloadProfileImageAndUploadS3`을 맨 아래로 두었습니다.

2024-10-19 08:53 UTC, Profile-exe requested changes
인터셉터 및 리졸버 추가 코멘트 남겼습니다!

2024-10-19 08:53 UTC, Profile-exe commented on src/main/java/kakao/rebit/member/resolver/MemberInfoArgumentResolver.java
> +        token = token.substring(BEARER_PREFIX.length());  // Bearer 제거
`request`에서 토큰을 추출하고 반환하는 로직은 `jwtTokenProvider`에서 해야되지 않나 생각합니다!

2024-10-19 08:53 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/jwt/JwtInterceptor.java
> +        return jwtTokenProvider.validateToken(token.substring(BEARER_PREFIX.length()));
이 부분도 `jwtTokenProvider`에서 토큰 추출 로직을 둔 뒤, 해당 검증로직 분기들을 토큰 추출 메서드 내부에 두면 좋을 것 같습니다.

2024-10-19 09:26 UTC, Profile-exe approved these changes

2024-10-19 09:27 UTC, kangboom commented on src/main/java/kakao/rebit/auth/jwt/JwtInterceptor.java
> +        return jwtTokenProvider.validateToken(token.substring(BEARER_PREFIX.length()));
[23d2a54](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/23d2a5493ad263fcd0c7a322f1dca38d78083bec): 반영했습니다!

2024-10-19 09:27 UTC, kangboom commented on src/main/java/kakao/rebit/member/resolver/MemberInfoArgumentResolver.java
> +        token = token.substring(BEARER_PREFIX.length());  // Bearer 제거
[23d2a54](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/96/commits/23d2a5493ad263fcd0c7a322f1dca38d78083bec): 반영했습니다!

2024-10-21 07:52 UTC, Wonmoan approved these changes
작업량이 많은데 고생하셨습니다. 컴포넌트별로 역할이 명확하게 잘 구분되어 있고
참고사항에 변경 사항을 상세히 적어주셔서 이해하기 좋았습니다. 검증과 예외 처리 또한 상황에 맞게 잘 작성해주신 것 같습니다.

S3 이미지 파일 삭제 순서를 피드를 먼저 삭제한 후 S3에서 이미지 파일을 삭제하는 방식으로 변경한 것, 트랜잭션 롤백을 고려한 좋은 방법인 것 같습니다.
또, 사진 조회가 필요한 요청은 presignedUrl을 포함한 DTO를 사용하고, 이미지가 필요하지 않은 다른 영역에서는 presignedUrl을 포함하지 않은 DTO로 나눠서 설계하신 부분도 좋은 방법인것 같습니다

시험 끝나고 조금 더 살펴보고 궁금한 사항 여쭤보겠습니다 정말 고생하셨습니다

2024-10-21 07:53 UTC, merged