[FEAT] 카카오 로그아웃 구현
kakao-tech-campus-2nd-step3/Team15_BE pull request #98
Opened 2024-10-24 13:05 UTC by seolbin96

## PR 유형
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 리팩토링
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 작업 내용 및 변경 사항
6주차 코드리뷰 반영 및 카카오 로그아웃 기능 구현했습니다.

## 이슈 링크
close #97 

## 참고사항
![image](https://github.com/user-attachments/assets/c17a4a40-ec70-45f7-b5c7-01d556206c72)

2024-10-24 13:30 UTC, Profile-exe requested changes
수고하셨습니다! 코멘트 확인 부탁드립니다.

2024-10-24 13:30 UTC, Profile-exe commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
다른 도메인들처럼 비즈니스 예외를 적용하는 것이 좋을 것 같습니다!

2024-10-24 13:30 UTC, Profile-exe commented on src/main/java/kakao/rebit/wishlist/service/BookWishlistService.java
>      }
기존 코드에서 해당 부분을 엔티티 내부로 뺀 것은 좋은 것 같은데, 저는 전체 로직을 갈아엎는게 적절하다 생각합니다.

현재 책을 특정할 수 있는 `isbn`이 있기 때문에, 이걸로 해당 책을 찾고
(`BookService`에서 `findByIsbnOrThrow` 등의 메서드 구현해 활용한다면 책 존재여부 검증 가능) 

회원을 `memberId`로 조회한다음
(여기서도 회원 서비스 활용 가능. `ArgumentResolver`를 거쳤으니 회원이 없다는 오류는 없을 수 있음)

리파지토리에서 해당 책과 회원에 해당하는 위시리스트를 가져오고 삭제하는건 어떨까요?
(쿼리메서드 구현)

2024-10-24 13:30 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/service/KakaoApiClient.java
> +    }
Kakao Developers에 백엔드 주소만 등록이 되어있던데, `Logout Redirect URI`에 프론트 주소도 추가해야될 것 같습니다!

2024-10-24 13:30 UTC, Profile-exe commented on src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
> +    }
`KakaoAuthService::kakaoLogout`, `KakaoApiClient::logout` 메서드 모두 `accessToken`을 사용하지 않는 같은데 파라미터로 받는 이유가 있을까요?

2024-10-25 04:17 UTC, kangboom requested changes
시험 기간인데 고생하셨습니다~~

2024-10-25 04:17 UTC, kangboom commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
>          diaryRepository.save(diary);
JPA의 더티 체킹에 의해 자동으로 변환된 부분을 반영해주기 때문에 다시 `save`를 호출하지 않아도 됩니다!

2024-10-25 04:17 UTC, kangboom commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
> +    }
이 부분은 dto 내부에서 Validation을 통해 검증하면 좋을 것 같습니다.

2024-10-25 04:17 UTC, kangboom commented on src/main/java/kakao/rebit/auth/service/KakaoApiClient.java
> +    private static final String LOGOUT_URL_TEMPLATE = "https://kauth.kakao.com/oauth/logout?client_id=%s&logout_redirect_uri=%s";
이 부분도 다른 부분처럼 환경 변수로 다루면 좋을 것 같습니다.

2024-10-25 04:17 UTC, kangboom commented on src/main/java/kakao/rebit/auth/service/KakaoApiClient.java
kakao 토큰 뿐만 아니라 저희 서비스의 token도 만료 시켜야 되는 거 아닌가요??

2024-10-25 06:34 UTC, Wonmoan reviewed
고생하셨습니다!

2024-10-25 06:36 UTC, Wonmoan reviewed
고생하셨습니다!

2024-10-25 06:36 UTC, Wonmoan commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
> +            new IllegalArgumentException(String.format("ISBN %s 에 해당하는 책을 찾을 수 없습니다.", diaryRequest.isbn())));
`DIARY_NOT_FOUND_MESSAGE` 와 비슷하게 
`"ISBN %s 에 해당하는 책을 찾을 수 없습니다."` 에 대한 내용도
상수로 추가해 예외 메시지 던지는 건 어떨까요

2024-10-25 07:26 UTC, seolbin96 commented on src/main/java/kakao/rebit/auth/service/KakaoApiClient.java
> +    }
추가했습니다!

2024-10-25 07:28 UTC, seolbin96 commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
[bf83f59](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/bf83f593933340be17b901e0f4092192bdf6e33e)
[a7def95](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/a7def95e5dc2052782594c01c05bab1507254d9a)
수정했습니다!

2024-10-25 07:32 UTC, seolbin96 commented on src/main/java/kakao/rebit/wishlist/service/BookWishlistService.java
>      }
[5fdf559](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/5fdf559f235038a72feab32196d9ad198436f22e)
[6e8de07](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/6e8de072ac72abdc16531a8dd71ea206a7f55090)
[2d7e04e](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/2d7e04e74f31aa1703da4681c5d96dd976e39dbf)

구체적인 피드백 감사합니다!! 반영하였습니닷

2024-10-25 07:34 UTC, seolbin96 commented on src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
> +    }
[8e77e07](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/8e77e079c758127989b450316bc1b78e6800c25a)
[8e77e07](https://github.com/kakao-tech-campus-2nd-step3/Team15_BE/pull/98/commits/8e77e079c758127989b450316bc1b78e6800c25a)

공식 문서에 `일반 로그아웃`과 `카카오 계정과 함께 로그아웃` 이렇게 두가지 방법이 있는데 일반 로그아웃은 엑세스토큰이 필요하고 카카오계정과 함께 로그아웃은 필요하지 않더라구요..! 제가 문서를 읽다가 헷갈린 것 같습니다ㅠ 수정하였습니다!!

2024-10-25 07:35 UTC, Profile-exe commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
재수정 부탁드립니다! "다른 도메인들처럼" 이라고 언급 드렸는데, 현재 사용 방법이 통일되지 않은 것 같습니다.

#72 
#73 
#81 

위 PR 참고하시면 될겁니다.

2024-10-25 07:38 UTC, Profile-exe requested changes

2024-10-25 07:38 UTC, Profile-exe commented on src/main/java/kakao/rebit/diary/service/DiaryService.java
추가로 다른 도메인들 처럼 회원 ID, 다이어리 ID를 감추는게 좋을 것 같습니다.
```java
"회원 ID %d 에 해당하는 다이어리 ID %d 를 찾을 수 없습니다."
```

위 내용은
```java
"해당 독서 일기를 찾을 수 없습니다."
```

로 바꿀 수 있을 것 같습니다.

2024-10-25 07:41 UTC, Profile-exe commented on src/main/java/kakao/rebit/wishlist/service/BookWishlistService.java
>      }
`memberService`, `bookService`를 호출하는데, 이를 사용하지 않고있습니다.
`findByMemberAndBook`이 적절하지 않나 생각합니다!

그리고 존재할때만 삭제하기보다는 존재하지 않는 경우 찾을 수 없다는 비즈니스 예외를 던지는게 좋을 것 같은데 설빈님 의견이 궁금합니다.

2024-10-25 07:44 UTC, merged